### ISSUE TITLE
any audio node as source

### ISSUE THREAD

**Issue by belm0** [chris-rudmin/opus-recorder#103]
README states:  "A javascript library to encode the output of Web Audio API nodes in Ogg Opus or WAV format", but I haven't found a way to provide arbitrary audio nodes as source.  The original library by mattdiamond accepted the source node in the Recorder constructor.

My use case is to capture the output of a web audio synthesizer.

**Comment by chris-rudmin** [comment]
Init the stream, and then connect your node to to script processor and optionally the monitor node:

```
var rec = new Recorder();
rec.initStream().then(function(stream){
    rec.sourceNode = customStreamSource;
    rec.sourceNode.connect( rec.scriptProcessorNode );
});
```

**Comment by belm0** [comment]
Thank you.  I encountered a few problems:  connected audio nodes must originate from the same context, and the app requires microphone permission even though it isn't used.

```Uncaught (in promise) DOMException: Failed to execute 'connect' on 'AudioNode': cannot connect to a destination belonging to a different audio context.```

Would you consider adding a source parameter or option to the constructor, and in that case avoid requesting the mic media and use the source's context?

**Comment by chris-rudmin** [comment]
I see. Feel free to make a pull request that satisfies your requirements. I
would be happy to review it.

**Comment by chris-rudmin** [comment]
@belm0 I just had a thought that if you just want to use the encoder, but not the recorder, you can instantiate the webworker and pass raw buffers to it for encoding.  Should achieve what you are looking for.  Check src/recorder.js for implementation example.
