### ISSUE TITLE
iOS Issue, Works Fine In Safari on Mac

### ISSUE THREAD

**Issue by maxmatthews** [chris-rudmin/opus-recorder#107]
I'm having trouble getting RecorderJS to work on iOS. The code runs fine in Safari, Chrome, and Firefox on Mac, but doesn't run on iOS. 
If I use the OGG encoder, the buffer size is always 165 regardless of how long the recording is.
```js
this.recorder.addEventListener("dataAvailable", e => {
    let dataBlob = new Blob([e.detail], { type: "audio/ogg" });
    this.audioBlob = dataBlob;

    console.log(dataBlob);
});
```
Returns on iOS 11: `Blob {size: 165, type: "audio/ogg", slice: function}`

Could the issue possibly be that I'm using React and need to initialize the encoder differently? Just stumped as to why it works fine in Safari 11 on Mac, but not iOS. 

I've also tried to use the `waveWorker.min.js` but upon the the `dataAvailable` event the following error appears in the console: `TypeError: undefined is not an object (evaluating 'this.recordedBuffers[0].length')`

I'm including the following files in my `index.html`:
```html
  <script src="./recorder.min.js"></script>
  <script src="./encoderWorker.min.js"></script>
  <script src="./waveWorker.min.js"></script>
```

Thanks in advance for your help!

**Comment by chris-rudmin** [comment]
Are you using iOS11 Safari?  Can you tell me if the example page works for you? http://rawgit.com/chris-rudmin/Recorderjs/master/example/encoder.html

**Comment by maxmatthews** [comment]
Yes, I'm using iOS 11.2 Safari. The example works for me which is why I was wondering it's an issue with React to get the Web Workers working.

**Comment by chris-rudmin** [comment]
Not sure if this is your problem, but the worker scripts are loaded dynamically, you should only need `<script src="./recorder.min.js"></script>`

**Comment by chris-rudmin** [comment]
or I guess in react world `require('recorder.min')`

**Comment by maxmatthews** [comment]
I took out the extra script tags and I'm still having the problem.

**Comment by maxmatthews** [comment]
@brancusi Was able to get it working in https://github.com/chris-rudmin/Recorderjs/issues/26 so I'm not sure if he can shed any light on it.

**Comment by chris-rudmin** [comment]
Care to share the whole console output? Also do you see any network errors, `404`s etc.

**Comment by maxmatthews** [comment]
Here is the `console.log(e)` and `console.log(dataBlob)` in the `dataAvailable` callback using the ogg encoder. No 404 errors. The highlighted blob retrieval that is failed I think is expected because I try to play an ogg file. 
<img width="525" alt="screen shot 2017-12-05 at 4 44 13 pm" src="https://user-images.githubusercontent.com/4709710/33632612-282cd374-d9dc-11e7-843b-5a484eed9588.png">
<img width="1453" alt="screen shot 2017-12-05 at 4 47 20 pm" src="https://user-images.githubusercontent.com/4709710/33632616-2af5c3ae-d9dc-11e7-9097-c15e518a2a6a.png">

**Comment by chris-rudmin** [comment]
Hmm, nothing there that tells me anything.

My next theory is that emscripten does some some environment checking to run the correct code to execute the wasm file. Having RecorderJS running inside react might be fooling the emscripten generated code. You might google for issues regarding emscripten and react.

To really divine the problem I think we would need to step through the generated code in `encoderWorker.min.js` to see where it fails.

**Comment by maxmatthews** [comment]
Would it help if I stripped out the sensitive parts of my react code and posted it? It's only about 200 lines and it's a single page app. May serve as a good example for other people trying to use this in React.

**Comment by chris-rudmin** [comment]
If you can host a gist which replicates the problem I can take a look at it, or if you don't mind leaving your dev ngrok open I can try and connect to your machine.

**Comment by maxmatthews** [comment]
Why can't GitHub have DMs? 😫
I can leave my ngrok open for the next hour. The URL is https://4ac2f9bd.ngrok.io/?_id=951
Should run fine in any desktop browser but only record blob sizes of 165 on iOS: https://4ac2f9bd.ngrok.io/?_id=951

**Comment by chris-rudmin** [comment]
Unfortunately I don't have time to look at it right now.  If you can share
the react code which replicates the problem, I can give it a go later on.
Thanks!

**Comment by maxmatthews** [comment]
Will do. I'll post the code later tonight! Thanks for your help!

**Comment by chris-rudmin** [comment]
@maxmatthews We're you able to sort out your issues?

**Comment by chris-rudmin** [comment]
@maxmatthews Feel free to re-open this issue if you can add an example which replicates the problem.
