### ISSUE TITLE
Chrome warning: GainNode.gain.value setter smoothing is deprecated

### ISSUE THREAD

**Issue by mreinstein** [chris-rudmin/opus-recorder#109]
[Deprecation] GainNode.gain.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.

**Comment by chris-rudmin** [comment]
I don't see this as an issue. Instantaneous value change is the expected behaviour based on the spec for GainNode.

**Comment by mreinstein** [comment]
> I don't see this as an issue

As long as chrome doesn't remove the feature after deprecation I agree, not a big issue. Will leave that to you!

**Comment by chris-rudmin** [comment]
@mreinstein Thanks for the the bug reports and pull requests! I appreciate them
