### ISSUE TITLE
maintaining recorderjs?

### ISSUE THREAD

**Issue by mreinstein** [chris-rudmin/opus-recorder#112]
@chris-rudmin I reached out to @mattdiamond via email, to see if he'd have interest in letting you and/or I co-maintain his Recorderjs module. He has a link to several forks of Recorderjs, and yours is by far the most active fork. Is this something you'd be interested in?

I'm not sure what the code changes would look like; I know you added opus related stuff to Recorderjs. Maybe it's just a matter of merging all your changes into Matt's original repo?

Anyway, let me know what you think..

**Comment by chris-rudmin** [comment]
@mreinstein A couple of years ago when I started this fork, I made some pull requests to @mattdiamind RecorderJS which never got merged. Since then, this module has been completely rewritten and is now focused on something quite different: OggOpus encoding/decoding.
All that to say I don't think any sensible merge is possible at this time.

**Comment by mreinstein** [comment]
ah ok, I guess a merge back probably doesn't make sense then. It might be good to just rename the repo to match the npm module name you published. chris-rudmin/opus-recorder perhaps?

**Comment by chris-rudmin** [comment]
Yeah, I've considered it, but I still get most of my traffic here from the original RecorderJS page. I would hate to lose that and mess that up and lose any Interest I get from keeping the RecorderJS name.

**Comment by mreinstein** [comment]
> I would hate to lose that and mess that up and lose any Interest I get

I think renaming a repo automatically redirects traffic from your old project (chris-rudmin/Recorderjs) to whatever new name you choose (e.g., chris-rudmin/opus-recorder)

**Comment by chris-rudmin** [comment]
Ah I wasn't aware. :)
