### ISSUE TITLE
Two short pages back to back when streaming streamPages: true

### ISSUE THREAD

**Issue by TxAg12** [chris-rudmin/opus-recorder#113]
Howdy,

When I use streamPages: true, about 150-180ms after the start event, **there are two dataAvailable events fired almost simultaneously**. The first is always an array of size 47, followed within a few ms of an array length 54. After this, the dataAvailable event usually fires as expected based on the maxBuffersPerPage setting.

Is this triggering of the dataAvailable by design? If so, I guess I will have to buffer this output as it something hitting that close together should be sent to the server in one message. It would be nice to be able to go straight from dataAvailable event to the messaging with the server without something in the middle to go wrong. Is there anyway to get just a single array with a length of 101 for the first event?

I read somewhere that the first frame is a headers for the container. I must admit that I do not know the details of Ogg as much as I should. I presume that's the reason for one of these.

Somewhat unrelated, is there a way to reduce the initial latency of the first dataAvailable event to be less than 180ms? And when I make the maxBuffersPerPage too low (something like 4), then this latency might increase to around 300ms (which defeats the purpose of more frequent output) with the third dataAvailable event occurring perhaps 40ms after the 2nd (and then it goes to expected timing).

I have not explored the worker files in sufficient depth. Ideally, it would be nice to take advantage of the low latency offered by Ogg Opus; however, right now it looks like I will need around a 500 ms buffer on the listening side. 

Any ideas about these two issues? Or am I fouling up my implementation?

Here's my initiation code. Note that I also leave the stream open.

        monitorGain: 0,
        numberOfChannels: 1,
        encoderPath: "./dist/encoderWorker.min.js",
        leaveStreamOpen: true,
	streamPages: true,
	maxBuffersPerPage: 6,
	encoderSampleRate:  8000,
	encoderApplication: 2048

Here's an example of the timing:

04:55:50.033 Unmute 
04:55:50.035 Recorder Start Event
04:55:50.179 Ogg Page Data Available Uint8Array(47) [79, 103, 103, 83, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 73, 183, 125, 185, 0, 0, 0, 0, 125, 62, 71, 79, 1, 19, 79, 112, 117, 115, 72, 101, 97, 100, 1, 1, 0, 15, 128, 187, 0, 0, 0, 0, 0]
04:55:50.180 Ogg Page Data Available Uint8Array(54) [79, 103, 103, 83, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 73, 183, 125, 185, 1, 0, 0, 0, 237, 47, 219, 52, 1, 26, 79, 112, 117, 115, 84, 97, 103, 115, 10, 0, 0, 0, 82, 101, 99, 111, 114, 100, 101, 114, 74, 83, 0, 0, 0, 0]
04:55:50.572 Ogg Page Data Available Uint8Array(203) [79, 103, 103, 83, 0, 0, 192, 93, 0, 0, 0, 0, 0, 0, 73, 183, 125, 185, 2, 0, 0, 0, 50, 40, 255, 15, 25, 7, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 8, 11, 228, 185, 160, 188, 132, 8, 7, 198, 179, 14, 198, 8, 7, 198, 179, 14, 198, 8, 7, 198, 179, 14, 198, 8, 7, 198, 179, 14, 198, 8, 7, 198, 179, 14, 198, 8, 7, 198, 179, 14, 198, 8, 7, 198, 179, 14, …]
04:55:51.083 Ogg Page Data Available Uint8Array(209) [79, 103, 103, 83, 0, 0, 64, 191, 0, 0, 0, 0, 0, 0, 73, 183, 125, 185, 3, 0, 0, 0, 123, 157, 37, 23, 26, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 8, 7, 198, 179, 14, 198, 8, 7, 198, 179, 14, 198, 8, 7, 198, 179, 14, 198, 8, 7, 198, 179, 14, 198, 8, 7, 198, 179, 14, 198, 8, 7, 198, 179, 14, 198, 8, 7, 198, 179, 14, 198, 8, 7, 198, 179, 14, …]
04:55:51.593 Ogg Page Data Available Uint8Array(202) [79, 103, 103, 83, 0, 0, 0, 29, 1, 0, 0, 0, 0, 0, 73, 183, 125, 185, 4, 0, 0, 0, 39, 189, 109, 67, 25, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 8, 7, 198, 179, 14, 198, 8, 7, 198, 179, 14, 198, 8, 7, 198, 179, 14, 198, 8, 7, 198, 179, 14, 198, 8, 7, 198, 179, 14, 198, 8, 7, 198, 179, 14, 198, 8, 7, 198, 179, 14, 198, 8, 7, 198, 179, 14, 198, …]
04:55:51.769 Mute 
04:55:51.772 Ogg Page Data Available Uint8Array(118) [79, 103, 103, 83, 0, 4, 192, 77, 1, 0, 0, 0, 0, 0, 73, 183, 125, 185, 5, 0, 0, 0, 38, 117, 182, 56, 13, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 8, 7, 198, 179, 14, 198, 8, 7, 198, 179, 14, 198, 8, 7, 198, 179, 14, 198, 8, 7, 198, 179, 14, 198, 8, 7, 198, 179, 14, 198, 8, 7, 198, 179, 14, 198, 8, 7, 198, 179, 14, 198, 8, 7, 198, 179, 14, 198, 8, 7, 198, 179, 14, 198, 8, 7, 198, 179, 14, 198, …]
04:55:51.776 Recorder Stop Event

**Comment by chris-rudmin** [comment]
The first two pages are ogg opus headers and are emitted as soon as they are generated.

A few things which might reduce latency:
- Reduce `bufferLength` to as small as your device can support
- Use legacy asm.js version `1.2` instead of WASM version.  The WASM version loads asynchronously and is slightly slower to startup.
- Specify `encoderApplication=2051` which a specific low latency mode
- Specify `resampleQuality=0` for fastest resampling
- Do not specify an `encoderSampleRate`. The lowest latency will be achieved if you can skip the resampling by setting your target device to 48000 Hz sample rate.
- You can try reducing the `encoderFrameSize`. It defaults to 20ms, but some latency gains might be had if you reduce this

I am curious to know how low you can get this! Good luck

**Comment by chris-rudmin** [comment]
Also, you should be aware that the latency for the first packet is not indicative of the streaming latency. This lib needs some time to init the WASM scripts and init the mic stream.

**Comment by TxAg12** [comment]
Dear Chris:

Thank you for the excellent tips and getting back so fast.

So the 2 separate header page events are by design. On review, the only differences between files for the first two pages is the serial number and the checksum, so I'll just create the first two frames on the server (based on the third page) and disregard uploading the first two pages.

I'll try eliminating the resampling, but I assume most of the delay is in the initiation of the scripts.

I noticed in the network console that it is loading both encoderWorker.min.js and encoderWorker.min.wasm every time I give it a start command even though I left it initiated (leaveStreamOpen). The biggest gains I think will be to leave this loaded, even if it means it is always encoding.

**Do you have a suggestion about what all needs to be changed to accomplish persistence of the worker?** 

I am actually using this on NWJS for a desktop app, so I can be liberal with resources. Your implementation is substantially better than the native MediaRecorder. It's a lot easier too. You did a great job with this.

Once I figure out how to cut the initial delay, I'll run all sorts of tests with toned audio files to determine delay and latency.

Justin

**Comment by chris-rudmin** [comment]
Unfortunately it's not so straight ahead to preload the worker and wasm because they both contain stateful information. It could be done by creating the worker in `initStream()` instead of `start()` however there might be some edge cases to be wary of before this works 100%.

**Comment by TxAg12** [comment]
I will work towards that and share any developments in a new thread.

Disposition of OP is that the back to back dataAvailable events are by design due to two Opus header pages followed by the first data page.

**Comment by chris-rudmin** [comment]
@TxAg12 I made changes to preload the workers if you would like to test it out:
https://github.com/chris-rudmin/opus-recorder/tree/preload-worker

**Comment by TxAg12** [comment]
@chris-rudmin Wow!

Really, wow!

I think that branch is substantially better. I spend 2-3 hours testing/comparing it to the current master with various settings.

I think this new method will remove on average almost a 1/2 second of delay from the time between recorder start event and the first real data page.

The following gave me essentially the best I could get in terms of latency and interval between pages:

```
 numberOfChannels: 1,
leaveStreamOpen: true,
streamPages: true,
maxBuffersPerPage: 1,
encoderSampleRate: 8000,
encoderApplication: 2051,
```

With this, you average a .080 second interval between pages but that varies between .070 and .090 (it likes .090 a lot). With the new version, the time between recorder start and first data page is around 0.130 seconds, varying from as low as around 0.100 to around 0.180 seconds. For the old version, it's about 0.450 seconds from start to the first data page. This is variable anywhere from perhaps 0.250 to 1 second. So a substantial improvement.

This seems to verify with the time it takes for the scripts to reload and issue the new header pages after the stop event, which is on average around 0.300 seconds but can vary from 0.150 to about a second. SO I think this nicely explains the gains.

As for other small gains, I do think 2051 saves you 5-10ms. I don't think the resampler matters much. In fact, I read in one document that when in CELT mode (48000Hz) there is a built in 4ms delay to account for the resampling time when in SILK mode (speech, lower sample rates).

Frame sizes below 20ms did not seem to help other than making for larger file sizes, and 60ms probably added a corresponding delay. I didn't run enough tests to confirm.

Obviously the maxBuffersPerPage is going to have the largest influence.

For clarity of other readers, this new version initializes the encoding workers immediately after a stop event and creates the two header frames. Previously, this occurred at the recorder start event.

I am very impressed and will be using the new version. I did not have any hiccups with it.

**Comment by TxAg12** [comment]
This was at 48000Hz, but for example. In the second startup, 96ms delay with the next interval 80ms. That's awesome IMO.

This was at 48000Hz, but for example:

> 
> (Recording)
> 21:00:23.886  Ogg Page Data Available
> 21:00:23.886  Uint8Array(672) [79, 103, 103, 83, 0, 0, 0, 108, 12, 0, 0, 0, 0, 0, 85, 242, 161, 132, 200, 0, 0, 0, 70, 197, 36, 187, 4, 159, 196, 158, 128, 248, 122, 66, 117, 187, 93, 67, 210, 217, 125, 187, 20, 250, 223, 96, 43, 132, 67, 70, 8, 208, 252, 123, 244, 213, 141, 15, 166, 2, 47, 191, 0, 139, 222, 53, 186, 73, 162, 149, 53, 208, 88, 2, 189, 141, 95, 225, 44, 252, 100, 234, 155, 236, 161, 88, 62, 237, 11, 253, 185, 236, 27, 89, 159, 102, 231, 190, 14, 83, …]
> 21:00:23.888  Ogg Page Data Available
> 21:00:23.888  Uint8Array(27) [79, 103, 103, 83, 0, 4, 255, 255, 255, 255, 255, 255, 255, 255, 85, 242, 161, 132, 201, 0, 0, 0, 109, 58, 49, 128, 0]
> **21:00:23.890  Recorder Stop Event
> 21:00:24.371  Ogg Page Data Available**
> 21:00:24.371  Uint8Array(47) [79, 103, 103, 83, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 199, 185, 37, 242, 0, 0, 0, 0, 248, 192, 1, 13, 1, 19, 79, 112, 117, 115, 72, 101, 97, 100, 1, 1, 0, 15, 128, 187, 0, 0, 0, 0, 0]
> 21:00:24.372  Ogg Page Data Available
> 21:00:24.373  Uint8Array(54) [79, 103, 103, 83, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 199, 185, 37, 242, 1, 0, 0, 0, 245, 144, 24, 202, 1, 26, 79, 112, 117, 115, 84, 97, 103, 115, 10, 0, 0, 0, 82, 101, 99, 111, 114, 100, 101, 114, 74, 83, 0, 0, 0, 0]
> 
> 
> **21:00:57.828 Recorder Start Event
> 21:00:57.930  Ogg Page Data Available**
> 21:00:57.930  Uint8Array(672) [79, 103, 103, 83, 0, 0, 0, 15, 0, 0, 0, 0, 0, 0, 199, 185, 37, 242, 2, 0, 0, 0, 77, 89, 233, 75, 4, 171, 177, 165, 128, 248, 122, 211, 201, 107, 170, 72, 75, 64, 124, 26, 109, 97, 206, 129, 231, 4, 195, 202, 52, 2, 5, 222, 30, 150, 245, 73, 137, 249, 54, 98, 61, 39, 239, 62, 169, 195, 229, 21, 216, 22, 250, 119, 232, 252, 236, 198, 235, 179, 140, 172, 38, 132, 4, 75, 183, 105, 250, 98, 87, 20, 219, 245, 210, 234, 138, 200, 55, 174, …]
> 21:00:58.010  Ogg Page Data Available
> 21:00:58.011  Uint8Array(510) [79, 103, 103, 83, 0, 0, 0, 30, 0, 0, 0, 0, 0, 0, 199, 185, 37, 242, 3, 0, 0, 0, 254, 2, 35, 159, 4, 129, 128, 129, 93, 248, 213, 187, 120, 201, 79, 203, 231, 160, 125, 63, 134, 7, 197, 113, 192, 24, 150, 89, 132, 122, 185, 43, 136, 224, 100, 80, 134, 186, 23, 64, 70, 186, 53, 36, 190, 58, 167, 67, 231, 189, 181, 177, 39, 102, 132, 239, 30, 129, 12, 68, 179, 93, 37, 50, 166, 33, 4, 72, 24, 210, 247, 227, 200, 202, 27, 206, 143, 86, …]
> 21:00:58.099  Ogg Page Data Available
> 21:00:58.180  Ogg Page Data Available
> 
> (…clip…)
> 
> 21:01:02.360  Ogg Page Data Available
> 21:01:02.450  Ogg Page Data Available
> 21:01:02.531  Ogg Page Data Available
> 21:01:02.620  Ogg Page Data Available
> 21:01:02.700  Ogg Page Data Available
> 21:01:02.790  Ogg Page Data Available
> 21:01:02.791  Uint8Array(543) [79, 103, 103, 83, 0, 0, 64, 158, 3, 0, 0, 0, 0, 0, 199, 185, 37, 242, 59, 0, 0, 0, 145, 221, 242, 63, 4, 128, 128, 128, 128, 248, 68, 190, 124, 191, 100, 244, 214, 4, 151, 250, 73, 163, 218, 173, 55, 119, 61, 156, 72, 5, 248, 29, 218, 67, 94, 249, 139, 66, 19, 218, 225, 80, 70, 23, 68, 32, 62, 5, 251, 153, 30, 144, 47, 26, 9, 196, 6, 25, 137, 199, 93, 190, 153, 122, 172, 36, 201, 164, 216, 37, 59, 84, 68, 65, 96, 20, 124, 65, …]
> 21:01:02.879  Ogg Page Data Available
> 21:01:02.880  Uint8Array(637) [79, 103, 103, 83, 0, 0, 64, 173, 3, 0, 0, 0, 0, 0, 199, 185, 37, 242, 60, 0, 0, 0, 84, 120, 169, 134, 4, 161, 126, 155, 164, 248, 223, 175, 221, 103, 100, 195, 43, 50, 86, 214, 246, 29, 6, 55, 235, 1, 175, 52, 244, 119, 230, 95, 78, 115, 236, 44, 128, 194, 217, 39, 53, 203, 121, 254, 229, 64, 152, 62, 141, 16, 12, 223, 104, 80, 156, 19, 143, 201, 220, 241, 150, 61, 178, 204, 81, 150, 78, 25, 92, 126, 114, 243, 81, 14, 190, 84, 96, 244, …]
> 21:01:02.950 Mute 
> 21:01:02.953  Ogg Page Data Available
> 21:01:02.954  Uint8Array(580) [79, 103, 103, 83, 0, 0, 64, 188, 3, 0, 0, 0, 0, 0, 199, 185, 37, 242, 61, 0, 0, 0, 198, 19, 176, 229, 4, 164, 128, 129, 128, 248, 223, 133, 48, 220, 255, 254, 179, 66, 246, 224, 142, 167, 32, 204, 166, 103, 39, 79, 129, 43, 59, 201, 3, 164, 54, 149, 14, 172, 17, 189, 197, 48, 101, 129, 215, 198, 132, 0, 194, 242, 140, 97, 219, 71, 160, 163, 213, 76, 144, 90, 241, 61, 196, 242, 145, 84, 111, 113, 190, 135, 97, 42, 210, 133, 179, 166, 72, 199, …]
> 21:01:02.955  Ogg Page Data Available
> 21:01:02.955  Uint8Array(27) [79, 103, 103, 83, 0, 4, 255, 255, 255, 255, 255, 255, 255, 255, 199, 185, 37, 242, 62, 0, 0, 0, 138, 14, 105, 251, 0]
> **21:01:02.957  Recorder Stop Event
> 21:01:03.689  Ogg Page Data Available**
> 21:01:03.690  Uint8Array(47) [79, 103, 103, 83, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 217, 67, 35, 187, 0, 0, 0, 0, 136, 193, 3, 216, 1, 19, 79, 112, 117, 115, 72, 101, 97, 100, 1, 1, 0, 15, 128, 187, 0, 0, 0, 0, 0]
> 21:01:03.691  Ogg Page Data Available
> 21:01:03.691  Uint8Array(54) [79, 103, 103, 83, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 217, 67, 35, 187, 1, 0, 0, 0, 45, 35, 74, 80, 1, 26, 79, 112, 117, 115, 84, 97, 103, 115, 10, 0, 0, 0, 82, 101, 99, 111, 114, 100, 101, 114, 74, 83, 0, 0, 0, 0]
> 
> 
> **21:01:04.984  Recorder Start Event
> 21:01:05.080  Ogg Page Data Available**
> 21:01:05.080  Uint8Array(545) [79, 103, 103, 83, 0, 0, 0, 15, 0, 0, 0, 0, 0, 0, 217, 67, 35, 187, 2, 0, 0, 0, 206, 154, 139, 108, 4, 192, 105, 104, 113, 248, 124, 176, 28, 126, 47, 232, 113, 6, 159, 210, 55, 105, 83, 170, 245, 190, 148, 20, 252, 52, 74, 197, 167, 123, 224, 157, 177, 159, 56, 5, 104, 227, 188, 5, 120, 226, 196, 252, 75, 111, 234, 244, 194, 65, 59, 69, 65, 246, 106, 34, 62, 56, 99, 19, 241, 205, 254, 10, 115, 61, 49, 50, 152, 107, 198, 76, 24, 10, …]
> 21:01:05.160  Ogg Page Data Available
> 21:01:05.161  Uint8Array(672) [79, 103, 103, 83, 0, 0, 0, 30, 0, 0, 0, 0, 0, 0, 217, 67, 35, 187, 3, 0, 0, 0, 201, 177, 44, 71, 4, 202, 182, 129, 128, 248, 124, 176, 119, 84, 162, 30, 115, 51, 224, 218, 104, 13, 250, 12, 15, 89, 77, 219, 185, 130, 199, 195, 168, 0, 70, 77, 18, 180, 224, 242, 169, 128, 8, 154, 164, 204, 62, 18, 110, 50, 247, 36, 66, 233, 163, 45, 23, 196, 205, 40, 118, 188, 143, 128, 151, 61, 127, 178, 35, 152, 8, 237, 191, 17, 145, 173, 174, 116, …]
>

**Comment by chris-rudmin** [comment]
Cool. I don't like that the initial pages get published on instantiation. I will move that into `start` I think

**Comment by TxAg12** [comment]
I personally like it that way. I can grab the serial numbers and get the file setup server-side in advance. It also eliminates a larger bandwidth demand at the beginning of recording where you have 100 bytes of headers plus whatever the first data frame is.

Very noticeable improvement today. I hope you find it as valuable as I do.
