### ISSUE TITLE
builds from source on linux - then tests fail

### ISSUE THREAD

**Issue by rowntreerob** [chris-rudmin/opus-recorder#116]
wild guess node version (nvm) issue cause i had to add line to emsdk_env.sh to select node v9.0  in order to get the build && links to even run.

tail of stdout showing test errors ... 

 CCLD     libspeexdsp.la
make[3]: Leaving directory '/home/rob/src/tmp/Recorderjs/speexdsp/libspeexdsp'
Making all in include
make[3]: Entering directory '/home/rob/src/tmp/Recorderjs/speexdsp/include'
Making all in speex
make[4]: Entering directory '/home/rob/src/tmp/Recorderjs/speexdsp/include/speex'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/rob/src/tmp/Recorderjs/speexdsp/include/speex'
make[4]: Entering directory '/home/rob/src/tmp/Recorderjs/speexdsp/include'
...
make[3]: Entering directory '/home/rob/src/tmp/Recorderjs/speexdsp'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/rob/src/tmp/Recorderjs/speexdsp'
make[2]: Leaving directory '/home/rob/src/tmp/Recorderjs/speexdsp'
make[1]: Leaving directory '/home/rob/src/tmp/Recorderjs/speexdsp'
npm run webpack -- --output-library EncoderWorker --output-library-target umd --optimize-minimize ./src/encoderWorker.js dist/encoderWorker.min.js

> opus-recorder@2.1.0 webpack /home/rob/src/tmp/Recorderjs
> webpack "--output-library" "EncoderWorker" "--output-library-target" "umd" "--optimize-minimize" "./src/encoderWorker.js" "dist/encoderWorker.min.js"

Hash: bc29afad494e0a1d1c78
Version: webpack 3.5.6
Time: 334ms
               Asset     Size  Chunks             Chunk Names
encoderWorker.min.js  8.23 kB       0  [emitted]  main
   [0] ./src/encoderWorker.js 11.9 kB {0} [built]
   [1] (webpack)/buildin/global.js 509 bytes {0} [built]
emcc -o dist/encoderWorker.min.js -O3 --llvm-lto 1 --memory-init-file 0 -s NO_DYNAMIC_EXECUTION=1 -s NO_FILESYSTEM=1 -s WASM=1 -s EXPORTED_FUNCTIONS="['_opus_encoder_create','_opus_encode_float','_opus_encoder_ctl','_speex_resampler_init','_speex_resampler_process_interleaved_float','_speex_resampler_destroy']" --pre-js dist/encoderWorker.min.js ./opus/.libs/libopus.a ./speexdsp/libspeexdsp/.libs/libspeexdsp.a
INFO:root:generating system library: wasm-libc.bc... (this will be cached in "/home/rob/.emscripten_cache/asmjs/wasm-libc.bc" for subsequent builds)
INFO:root: - ok
npm run webpack -- --output-library DecoderWorker --output-library-target umd --optimize-minimize ./src/decoderWorker.js dist/decoderWorker.min.js

> opus-recorder@2.1.0 webpack /home/rob/src/tmp/Recorderjs
> webpack "--output-library" "DecoderWorker" "--output-library-target" "umd" "--optimize-minimize" "./src/decoderWorker.js" "dist/decoderWorker.min.js"

Hash: 987425345c3d5408562f
Version: webpack 3.5.6
Time: 168ms
               Asset     Size  Chunks             Chunk Names
decoderWorker.min.js  5.79 kB       0  [emitted]  main
   [0] ./src/decoderWorker.js 7.86 kB {0} [built]
   [1] (webpack)/buildin/global.js 509 bytes {0} [built]
emcc -o dist/decoderWorker.min.js -O3 --llvm-lto 1 --memory-init-file 0 -s NO_DYNAMIC_EXECUTION=1 -s NO_FILESYSTEM=1 -s WASM=1 -s EXPORTED_FUNCTIONS="['_opus_decoder_create','_opus_decode_float','_opus_decoder_destroy','_speex_resampler_init','_speex_resampler_process_interleaved_float','_speex_resampler_destroy']" --pre-js dist/decoderWorker.min.js ./opus/.libs/libopus.a ./speexdsp/libspeexdsp/.libs/libspeexdsp.a
npm run webpack -- --output-library Recorder --output-library-target umd --optimize-minimize ./src/recorder.js dist/recorder.min.js

> opus-recorder@2.1.0 webpack /home/rob/src/tmp/Recorderjs
> webpack "--output-library" "Recorder" "--output-library-target" "umd" "--optimize-minimize" "./src/recorder.js" "dist/recorder.min.js"

Hash: c2beb91111ebcc06f503
Version: webpack 3.5.6
Time: 182ms
          Asset     Size  Chunks             Chunk Names
recorder.min.js  5.81 kB       0  [emitted]  main
   [0] ./src/recorder.js 6.02 kB {0} [built]
   [1] (webpack)/buildin/global.js 509 bytes {0} [built]
    + 1 hidden module
npm run webpack -- --output-library WaveWorker --output-library-target umd --optimize-minimize ./src/waveWorker.js dist/waveWorker.min.js

> opus-recorder@2.1.0 webpack /home/rob/src/tmp/Recorderjs
> webpack "--output-library" "WaveWorker" "--output-library-target" "umd" "--optimize-minimize" "./src/waveWorker.js" "dist/waveWorker.min.js"

Hash: 5b5321ff1bbdd8106b14
Version: webpack 3.5.6
Time: 265ms
            Asset     Size  Chunks             Chunk Names
waveWorker.min.js  2.88 kB       0  [emitted]  main
   [0] ./src/waveWorker.js 4.33 kB {0} [built]
   [1] (webpack)/buildin/global.js 509 bytes {0} [built]
# Tests need to run relative to `dist` folder for wasm file import
cd ./dist; node --expose-wasm ../test.js

  decoderWorker
    ✓ should initialize config
    1) should decode mono
    2) should decode stereo
    3) should decode joined file
    4) should decode two files

  encoderWorker
    5) should initialize config
    6) should initialize encoder
    7) should configure encoderBitRate
    8) should configure complexity
Makefile:32: recipe for target 'test' failed
make: *** [test] Error 1
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! opus-recorder@2.1.0 make: `make`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the opus-recorder@2.1.0 make script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rob/.npm/_logs/2017-12-23T22_05_06_472Z-debug.log

**Comment by chris-rudmin** [comment]
I don’t see anything particular from the logs. I had issues building with emscripten on the incoming branch. Not sure which version you are running but try from the latest tag.

**Comment by rowntreerob** [comment]
i checked out "2.1.0" set the emcc-debug-1 in env  and rebuilt.  No changes in result. Tests are still failing.


all looks ok  ... emcc steps and link steps seem Ok until the testrunner. There are new .min  and new .asm files in /dist  but after the first test for Decoder"initialize"  passes , they all fail.

I will use the encoder/decoder min files in a live project and see if they work??

i built this project from source and all was OK about 4 months ago. Now it fails. In that period , i started using nvm for tweeking node versions.

**Comment by rowntreerob** [comment]
i deleted the project, recloned, rebuilt and got same result 
 - build looks good links look good , ./dist contents below:

-rw-rw-r-- 1 rob rob   32612 Dec 24 10:57 decoderWorker.min.js
-rw-rw-r-- 1 rob rob  765143 Dec 24 10:57 decoderWorker.min.temp.asm.js
-rw-rw-r-- 1 rob rob  127760 Dec 24 10:57 decoderWorker.min.wasm
-rw-rw-r-- 1 rob rob   35319 Dec 24 10:57 encoderWorker.min.js
-rw-rw-r-- 1 rob rob 1424615 Dec 24 10:57 encoderWorker.min.temp.asm.js
-rw-rw-r-- 1 rob rob  219974 Dec 24 10:57 encoderWorker.min.wasm
-rw-rw-r-- 1 rob rob    5807 Dec 24 10:57 recorder.min.js
-rw-rw-r-- 1 rob rob    2884 Dec 24 10:57 waveWorker.min.js

ERROR in tests is still same stdout below

            Asset     Size  Chunks             Chunk Names
waveWorker.min.js  2.88 kB       0  [emitted]  main
   [0] ./src/waveWorker.js 4.33 kB {0} [built]
   [1] (webpack)/buildin/global.js 509 bytes {0} [built]
# Tests need to run relative to `dist` folder for wasm file import
cd ./dist; node --expose-wasm ../test.js


  decoderWorker
    ✓ should initialize config
    1) should decode mono
    2) should decode stereo
    3) should decode joined file
    4) should decode two files

  encoderWorker
    5) should initialize config
    6) should initialize encoder
    7) should configure encoderBitRate
    8) should configure complexity
Makefile:32: recipe for target 'test' failed
make: *** [test] Error 1
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! opus-recorder@2.1.0 make: `make`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the opus-recorder@2.1.0 make script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

attached the tail of the debug-build-log 
[make_Recorderjs_3.log](https://github.com/chris-rudmin/opus-recorder/files/1585029/make_Recorderjs_3.log)


log contains multiple instance of error below ( not emcc expert so i ignored the errors 

INFO:root:(Emscripten: Running sanity checks)
ERROR:root:no input files
note that input files without a known suffix are ignored, make sure your input files end with one of: ('.c', '.C', '.i', '.cpp', '.cxx', '.cc', '.c++', '.CPP', '.CXX', '.CC', '.C++', '.ii', '.m', '.mi', '.mm', '.mii', '/dev/null', '.bc', '.o', '.obj', '.lo', '.dylib', '.so', '.a', '.ll', '.h', '.hxx', '.hpp', '.hh', '.H', '.HXX', '.HPP', '.HH')

**Comment by chris-rudmin** [comment]
I see you are building with emscripten 1.37.26. The last successful build I
did was with 1.37.25. Can you confirm if that is working?

**Comment by rowntreerob** [comment]
thank you. that worked. 
reverted to emcc v 1.37.25... 

 all tests passed. build was fine.

**Comment by chris-rudmin** [comment]
@rowntreerob I fixed the makefile if you want to build from sdk-incoming-64bit.

**Comment by ZachMoreno** [comment]
@chris-rudmin I'm having a similar issue on MacOS High Sierra with both `make` & `make test`

```
npm test

> opus-recorder@4.0.0 test /Users/phobos/Desktop/clones/opus-recorder
> make test

# Tests need to run relative to `dist` folder for wasm file import
cd ./dist; node --expose-wasm ../test.js
node: bad option: --expose-wasm
make: *** [test] Error 9
```

I'm running emscripten 1.37.28

**Comment by chris-rudmin** [comment]
Emscripten install Node v4 into the path by default (There is a bug open
for this). You probably need to modify your PATH so it points to a newer
Node version. LTS is what is working for me.
