### ISSUE TITLE
encoderWorker.min.js should get the path to the .wasm

### ISSUE THREAD

**Issue by rotem925** [chris-rudmin/opus-recorder#117]
Hi,
If I'm changing the path to the encoder, it does not affect the wasm path.
What I'm trying to do is renaming encoderWorker.min.js, but encoderWorker.min.wasm is hard coded.

Is there an option to set the the wasm encoder path as well?

Thanks,
Rotem

**Comment by chris-rudmin** [comment]
Wasm name is built according to the min.js name. Can be changed in make
file.

**Comment by rotem925** [comment]
Hi @chris-rudmin ,
I'm trying to load the library from a different url, where the library sits in an upper level.
It seems to me that it tries to load wasm relatively to the encoderWorker.min.js
Do I miss something?
Thanks!

**Comment by rotem925** [comment]
@chris-rudmin 
It does work, sorry for misunderstanding... I'm closing that issue.
I've managed to tell Webpack to just replace the name when processing that file.
Thank you.
