### ISSUE TITLE
Using the decoder in a SPA

### ISSUE THREAD

**Issue by phal0r** [chris-rudmin/opus-recorder#119]
Hi,

thanks for this piece of software. It really helps me in my current project, where I need to encode several user recorded audio files. The encoder is working really smooth and I am trying to use the decoder for browsers like Safari and managed to produce this code:

```
var typedArray = new Uint8Array(buffer);
    var decodedData = [];
    that.decoder.onmessage = function(e){
      // null means decoder is finished
      if (e.data === null) {
        var raw = new Float32Array(decodedData.length * 4096);
        for(var i=0,len=decodedData.length;i<len;i++) {
          raw.set(decodedData[i], i * 4096);
        }
        var audioBuf = Wad.audioContext.createBuffer(1, raw.length, Wad.audioContext.sampleRate);

        if (typeof audioBuf.copyToChannel === "function") {
          audioBuf.copyToChannel(raw, 0, 0);
        } else { // Safari, Edge sometimes
          audioBuf.getChannelData(0).set(raw);
        }
        console.log(audioBuf);
        that.decoder.onmessage = null;
        return resolve(audioBuf);
      }
      // e.data contains decoded buffers as float32 values
      else {
        decodedData.push(e.data[0]);
      }
    };
    that.decoder.postMessage({
      command: 'decode',
      pages: typedArray
    }, [typedArray.buffer] );

    that.decoder.postMessage({
      command: 'done'
    });
```

Basically taken from your decoding example, but modified it to use it as an AudioBuffer directly instead of encoding it to wav. This works so far, but after sending the 'done' command 

```
    that.decoder.postMessage({
      command: 'done'
    });
```
The decoder worker closes itself. The encoder just sends one message, once encoding is finished, so it is easy to keep the worker alive and detect the end of the encoding. The decoder in contrast needs the 'done' command to send an empty message as marker of the end of decoding. Is there an intended way to keep the worker alive to use it for decoding several audio files while the app is running?

Thanks in advance!

**Comment by chris-rudmin** [comment]
The decoder is stateful, and each encoded file could have been encoded differently, so it is required to re-init the decoder for each new file.

**Comment by chris-rudmin** [comment]
If you join multiple files encoded with the same number of channels, they can be decoded with one instance of the decoder worker.

**Comment by chris-rudmin** [comment]
Could you tell me what would be the ideal behaviour? Worker posts `null` automatically at the end of each stream and stays listening for additional decoding?

**Comment by chris-rudmin** [comment]
As of v2.1.1 decoder now publishes null at the end of each stream and stays alive until the close command is received.

**Comment by phal0r** [comment]
Hi @chris-rudmin ,

wow, that fast, thank you! It is exactly as you described: The worker should stay alive and signal the end of the decoding process, so the calling function knows when the file is decoded. I will check it.

**Comment by phal0r** [comment]
Seems to work and I guess this part is not needed anymore, right? : 
```
that.decoder.postMessage({
      command: 'done'
    });
```

**Comment by chris-rudmin** [comment]
Done will send the last buffer and close the worker.
