### ISSUE TITLE
Check if WebAssemby Supported in IsRecordingSupported method

### ISSUE THREAD

**Issue by rotem925** [chris-rudmin/opus-recorder#124]
I think this has to be added to that method.
Browsers that do not support WebAssembly will not be able to use it.

Since you already have this method, I think this should be included..

Rotem

**Comment by chris-rudmin** [comment]
Good idea.  only `encoder.min.js` and `decoder.min.js` require webassembly.  `waveworker.min.js` does not require it.

**Comment by rotem925** [comment]
Great,
That method is static, so I don't know how you're going to check which endoder/decoder is used thought..
