### ISSUE TITLE
Add unminifed compiled sources to dist

### ISSUE THREAD

**Issue by zhukov** [chris-rudmin/opus-recorder#126]
Please consider adding unminified versions of compiled sources for those who use vanilla JS (without webpack/modules) but want to see sources. You might add it just to releases or right to `/dist`. I have my own uglifier for all vendor scripts altogether.

Nice reading on related topic: https://hackernoon.com/im-harvesting-credit-card-numbers-and-passwords-from-your-site-here-s-how-9a8cb347c5b5

PS. Thanks for your work, very useful library 👍

**Comment by chris-rudmin** [comment]
Great idea! Feel free to make a pull request.
