### ISSUE TITLE
audio display/visualization

### ISSUE THREAD

**Issue by hburgund** [chris-rudmin/opus-recorder#129]
Two related questions on visualization of audio data:
* I need to provide a visual representation of the audio input stream levels while recording (i.e. a level meter) and am wondering if you have a recommended approach. I could perhaps do this with a different `AudioContext` just for this purpose(?) and keep things separated from the actual recording, but I can imagine other more integrated approaches as well. 
* I would also like to display the recorded waveform after I'm done recording and the way I did this with the original `recorder.js` was to use the `recorder.getBuffer()` function (https://github.com/mattdiamond/Recorderjs/blob/master/dist/recorder.js#L132), but I don't see that in your version. Is there a replacement or other recommended approach for this? I can handle all the display stuff, I just wonder what the most convenient way of getting the full buffer data is post-recording.

**Comment by chris-rudmin** [comment]
@hburgund For your first question; You can probably achieve this by connecting your recording level meter to the source node `rec.sourceNode`.  

For your second question it would depend on if you are recording to opus or wav.  They would have different wave forms because one is lossy and one is lossless.

**Comment by hburgund** [comment]
@chris-rudmin thx for the response...I will try connecting to `rec.sourceNode`

I am recording only to wav at this point.

**Comment by chris-rudmin** [comment]
For rendering the recording to a waveform, are you using a lib?  There is https://wavesurfer-js.org/ which accepts a wav file. I imagine you can pass it the exported data and have it visualized.

**Comment by hburgund** [comment]
I was planning to not use another library, but rather take the raw buffer values and plot them using this code: https://github.com/cwilso/AudioRecorder/blob/master/js/audiodisplay.js

That said, I was actually planning to use wavesurfer for something else, so maybe that's the easiest approach.

Is there a reason you removed `getBuffer()`? I could consider putting it back in, but I'm guessing you had a good reason that probably means I shouldn't waste time trying to put it back in ;-). Thx.

**Comment by chris-rudmin** [comment]
I removed `getBuffer`, because opus audio is compressed. I didn't want the overhead of storing the raw buffers in memory in addition to the encoded audio.

**Comment by hburgund** [comment]
Makes sense...you've given me plenty to work with and I'm sure I can figure out the best solution from here. Thx a lot.

**Comment by ndkv** [comment]
Hello, is `rec.sourceNode` still the way for accessing the stream? It's not defined a.k.a. I can't find it in the latest version. I only see `rec.initSourceNode`.
