### ISSUE TITLE
Handle getUserMedia Errors

### ISSUE THREAD

**Issue by michael-ecb** [chris-rudmin/opus-recorder#134]
Hi,

When microphone disconnected  "getUserMedia"  throws a not handled "DevicesNotFoundError" exception,
Catch function is missing, is it possible to catch this error and fire onstreamerror or onerror? (line 198)

Thanks

**Comment by chris-rudmin** [comment]
There is error handling code for the `getUserMedia` stream.  Can you provide some steps to reproduce this?

**Comment by michael-ecb** [comment]
Hi,

Ok, I've investigated it a bit more...
the start() is now method returns a promise
if there is an error while starting, the onstreamerror event is fired, if everything is passed you fire the onstart event.

It is a bit confusing which should I use.
If I choose to use the event handlers you provided, I will also have to implement the catch on the promise, since there would be an error from the browser if I don't.

So currently I've registered the onstart event and onstreamerror event AND handling the start promise catch in order to have a quick fix.

I think this misleading, I would get rid of the promise return and just resolve it inside your code on line 252, instead of throwing it..

Actually I think the previous version handled better the errors.
What do you think?

**Comment by michael-ecb** [comment]
by the way...
If I'm using the events only and not the promise, there are some issues with the events ordering..

**Comment by michael-ecb** [comment]
Sorry for bringing all this up...
But I also saw that if there was an error , you do not set the state to inactive and then the start method does not return a promise..
Try to add the promise to your demo to see this:

`start.addEventListener( "click", function(){ recorder.start().catch(function(e){console.log(e)});`

**Comment by michael-ecb** [comment]
This is what I use now:

```javascript 
this.recorder.start()
        .then(()=>{
            this._recorder_onStart();
        }).catch((e)=>{
            this.recorder.state = 'inactive'; //PATCH
            this._recorder_streamError(e);
        });
```
As you ca see, I eliminated the use of the events and now use only the promise, and I added a patch for the inactive.

I tried to use the event handlers instead of the promise, but when there is a catch, on streamError I call the recorder.stop which cause a hang. I guess because of the promise event loop.

Maybe using Promise only instead of the events is better...
An example for you would be to add this to the example html on line 133

```javascript 
console.log('before stop');
recorder.stop();
console.log('After stop');
```

You will see that I'm here console is never called

**Comment by rotem925** [comment]
@chris-rudmin Have the exact same issue as mentioned...

**Comment by chris-rudmin** [comment]
Thanks for the feedback.  Indeed I think I will fix these issues by
removing the onstreamerror callback and stick with the promise. Also thanks
for catching the state error.

**Comment by rotem925** [comment]
Thank you @chris-rudmin, that was real quick and a great solution!

**Comment by michael-ecb** [comment]
@chris-rudmin  Thanks!
