### ISSUE TITLE
Use existing audio context

### ISSUE THREAD

**Issue by thijstriemstra** [chris-rudmin/opus-recorder#138]
I use opus-recorder in [videojs-record](https://github.com/collab-project/videojs-record).

It's a plugin called `opus-recorder-plugin.js`, see source at https://github.com/collab-project/videojs-record/blob/master/src/js/plugins/opus-recorder-plugin.js and live demo at https://collab-project.github.io/videojs-record/examples/audio-only-opus.html

I noticed a new version was available (4.0.0) so I tried upgrading but noticed a lot of functionality changed and it seems it's no longer possible to use an existing audio context (that is hooked up to a microphone for example). Any idea how I can achieve this with the latest version of this library?

**Comment by chris-rudmin** [comment]
Yes. `start()` now accepts an optional sourceNode. So pass any audioNode to `start()` and it will be used in place of setting up it's own context. This is a new feature, so please report any issues you might encounter.

**Comment by chris-rudmin** [comment]
A thing to note is that the audioContext will be closed at the end of recording unless you specify `leaveStreamOpen: true`

**Comment by thijstriemstra** [comment]
@chris-rudmin thanks I'll check it out and get back to you.

**Comment by thijstriemstra** [comment]
@chris-rudmin I've now created a new node:

```javascript
this.audioContext = new AudioContext();
this.audioSourceNode = this.audioContext.createMediaStreamSource(
    this.inputStream)
```

and pass it to `start`:

```javascript
this.engine.start(this.audioSourceNode);
```

But I'm seeing the following warnings in the console:

![opus-recorder-issue](https://user-images.githubusercontent.com/305679/35584174-7ffd7d9e-05f4-11e8-84fe-9c4d1dd6875f.png)

Can these be ignored or?

**Comment by chris-rudmin** [comment]
Does the recorder work? I never encountered such a warning, but it appears for streaming instantiation, that your webserver needs to server `.wasm` files with the mime type `application/wasm`

**Comment by thijstriemstra** [comment]
The recorder produces a blob like this:

```
Blob { lastModifiedDate: Date 2018-01-30T18:45:41.038Z, name: "1517337941038.ogg", size: 9, type: "audio/ogg" }
```

That size of 9 indicates it's broken..

**Comment by chris-rudmin** [comment]
Does your ondataavailable look like this ?
```
onRecordingAvailable(data) {
        let blob = new Blob([data], {type: 'audio/ogg'});
        ...
}
```

**Comment by thijstriemstra** [comment]
@chris-rudmin I'm still using the older version, that could be the issue:

```javascript
onRecordingAvailable(data) {
        // Opus format stored in an Ogg container
        let blob = new Blob([data.detail], {type: 'audio/ogg'});

        this.onStopRecording(blob);
    }
```
Let me check.

**Comment by thijstriemstra** [comment]
That fixed it, awesome. So basically the only 'error', or warning, I see is the screenshot with wasm, but it seems harmless.

**Comment by chris-rudmin** [comment]
awesome :)

**Comment by thijstriemstra** [comment]
![opus-error](https://user-images.githubusercontent.com/305679/36392615-6d0f18a6-15ac-11e8-9afd-0362aaca1123.png)

I'm now using 4.1.0 and seeing this error, making it unusable. Any idea @chris-rudmin? Live demo at https://collab-project.github.io/videojs-record/examples/audio-only-opus.html

**Comment by thijstriemstra** [comment]
Turns out the .wasm files were missing, mistake on my end.
