### ISSUE TITLE
Set recording volume / mute?

### ISSUE THREAD

**Issue by ZachMoreno** [chris-rudmin/opus-recorder#139]
In the README you document

`rec.setMonitorGain( gain )`
`setMonitorGain` will set the volume on what will be passed to the monitor. Monitor level does not affect the recording volume. Gain is an a-weighted value between 0 and 1.

How would I go about setting the recording volume & mute?

**Comment by ZachMoreno** [comment]
Would it be useful if I submitted a PR with the addition of a `rec.setMicrophoneGain( gain )` method?

**Comment by chris-rudmin** [comment]
Sure. Would be much appreciated.

**Comment by ZachMoreno** [comment]
Happy to, is there an existing approach that I can work from?

**Comment by ZachMoreno** [comment]
My current approach is to add a new `microphoneGain` property to the config object with a default value of `0.9`. Within the `initAudioGraph()` method we add a `microphoneNode` & a `mixerNode` just like the current `monitorNode`. We set the `microphoneGain` & we connect the  `microphoneNode` to the `mixerNode`. Once we have the `stream` in the `initSourceNode()` method, we connect it to the `microphoneNode`. Finally we can define the `setMicrophoneGain()` which is modeled after the `setMonitorGain()` method.

```
Recorder.prototype.setMicrophoneGain = function( gain ){
  this.config.microphoneGain = gain;

  if ( this.microphoneNode && this.audioContext ) {
    this.microphoneNode.gain.setTargetAtTime(gain, this.audioContext.currentTime, 0.01);
  }
};
```

& test

```
it('should set the microphone volume', function () {
  var rec = new Recorder();
  return rec.start().then(function() {
    rec.setMicrophoneGain(0.3);
    expect(this.microphoneNode.gain.value).to.be(0.3);
    expect(this.microphoneNode.gain.value).not.to.be(0.9);
  });
});
```

**Comment by ZachMoreno** [comment]
Here's my fork/branch for full context
https://github.com/ZachMoreno/opus-recorder/tree/vol-mute-ctrl

**Comment by ZachMoreno** [comment]
Turns out the `mixerNode` is unnecessary if we create a `volumeNode` & connect the `microphone` to it. Then return the `volumeNode` as the `sourceNode` rather than the `microphone`.

```
Recorder.prototype.setMicrophoneGain = function( gain ){
  gain = parseFloat( gain );
  this.config.microphoneGain = gain;

  if ( this.volumeNode && this.audioContext ) {
    this.volumeNode.gain.setTargetAtTime(gain, this.audioContext.currentTime, 0.01);
  }
};
```

& test

```
it('should set the microphone volume', function () {
  var rec = new Recorder();
  return rec.start().then(function() {
    rec.setMicrophoneGain(0.3);
    expect(rec.config.microphoneGain).to.equal(0.3);
    expect(rec.config.microphoneGain).not.to.equal(0.9);
  });
});
```

**Comment by ZachMoreno** [comment]
Thanks so much for working with me on this PR @chris-rudmin. I'm happy to contribute more & will keep an eye out for opportunities to improve.
