### ISSUE TITLE
iOS: Cannot record more than twice

### ISSUE THREAD

**Issue by kbumsik** [chris-rudmin/opus-recorder#141]
Hi,
I found out an issue with the recorder while testing it with my iPhone (iOS 11.3 Beta).
Apart from iOS11.2 issue #128  , The recording works well in iOS 11.3.

However, I can record it only once. I did two approaches:
1. set `leaveStreamOpen`
2. just re-initialize `Recorder`

both don't work after the first recording, When I do `rec.start()` after the first `rec.stop()` it outputs a recording file but the content of the recording is silent.

Does anybody know a workaround?

Thank you.
Bumsik Kim

**Comment by chris-rudmin** [comment]
I don't have iOS 11.3 at the moment to test this out. Perhaps in a few weeks I will be able to test that scenario and help you out.

**Comment by chris-rudmin** [comment]
@kbumsik Can you validate if you can reproduce the issue with the example opus recorder.
https://rawgit.com/chris-rudmin/Recorderjs/master/example/encoder.html

**Comment by chris-rudmin** [comment]
Tested with iOS 11.3. Was able to record twice with the example encoder.
