### ISSUE TITLE
Glitch in wave file when recording

### ISSUE THREAD

**Issue by nicolasgere** [chris-rudmin/opus-recorder#142]
Hi there, thanks for you usefull library

When i record long sentence like 20 seconde, i have some glitch in my wav file.
I dont know where that came from? I have that bug on my macbook air and not on a macbook pro, with same os and chrome version. Is that possible that the cpu is not enough fast?

Thanks

**Comment by chris-rudmin** [comment]
Does it occur in a browser using chromium?  Most likely related to this issue: https://bugs.chromium.org/p/chromium/issues/detail?id=637558#c62
