### ISSUE TITLE
macOS recording sounds weird

### ISSUE THREAD

**Issue by rotem925** [chris-rudmin/opus-recorder#143]
I'm trying the library using macOS Safari latest version (10.13.3)
The sound seems choppy after recording using your example (I've downloaded the opus file)

I think most of the issues are cause of the WebAssembly which removed a lot of browser support.

I've tried to take the encoderWorker from version 1.2 and it seems to work, didn't tested it heavily though..
Do you think what I did will work?
If yes, is there an option to include also the previous encoderWorker which used a Worker instead?
Can we(developer) choose the encoder, wether it is WebAssembly or a Worker?
If yes, then the IsRecordingSupported which check against WebAssembly should change as well.

Let me know what you think please.

Thank you
Rotem

**Comment by chris-rudmin** [comment]
Can you attack the recording with choppiness?  I am unable to reproduce on my mac here using Safari 11.0.3. To use the asm.js version stick to release v1.2.0.

**Comment by chris-rudmin** [comment]
@rotem925 Or if you want the latest recorder interface without wasm, you can build from the sources and specify `WASM=0` in the emscripten params.

**Comment by rotem925** [comment]
@chris-rudmin I can't reproduce it, it seems to be working ok now. I did have some files that had a bad and choppy quality. My team are now running some tests so I will let you know if we find something.

I like your idea about putting WASM=0 which will  let me use the latest interface version without WebAssembly. If that is the case I will have some issues since the Recorder is checking against global.WebAssembly to determine support for the browser(I asked it in a previous issue https://github.com/chris-rudmin/opus-recorder/issues/124).

But if the encoder can be replaced by us, I would recommend to remove that check.
Anyway I think it will be great if you could just include the no-wasm encoder in npm since there is no much support for WebAssembly and it would be easier to integrate.

We are planning to use this library heavily..

Thank you for all the hard work!

**Comment by rotem925** [comment]
@chris-rudmin I still have a workaround for the IsRecordingSupported static method.
I can override it... Didn't test it yet. Your choice.

**Comment by vodnicearv** [comment]
I also have a recording that cuts off in several places.

The problem is only in safari, chrome is fine
