### ISSUE TITLE
Impossible to load encoderWorker.min.asm on Android/Cordova

### ISSUE THREAD

**Issue by stephnicolas** [chris-rudmin/opus-recorder#144]
My application is running fine on chrome for windows but the same application on Android/Cordova failed to load the asm file encoderWorker.min.wasm

cordova.js:1 Fetch API cannot load file:///android_asset/www/js/opusrecorder/encoderWorker.min.wasm. URL scheme "file" is not supported.

Thanks
Stephane

**Comment by chris-rudmin** [comment]
I have never test Android/cordova, and it is not in the list of supported browsers.
I know for webpages, recordings can only been done by pages served over https. To get support for wasm execution in android/cordova over local file system you would be best to enquire in the emscripten project.

**Comment by stephnicolas** [comment]
Thank you Chris, after researches, I find out that it was an issue related to chromium Fetch API restriction
it appends at wasm module loading with fetch command

**Comment by LavaRiddle** [comment]
@stephnicolas - Based on your based research, how did you fair getting this to work on Cordova? I'm bumping into the same issue.

**Comment by f5cs** [comment]
hi @chris-rudmin:
  there is a resolved:
  convert encoderWorker.wasm from binary to base64（encoderWorkerBase64.wasm） and Assignment to a variable, 
then in encoderWorker.js,use importScripts('encoderWorkerBase64.wasm'）
after,:
var wasmBlod = atob(b64Data);
var reader = new FileReader(); 
var wasmArrayBuf = reader .readAsArrayBuffer(wasmBlod );

WebAssembly.instantiate(wasmArrayBuf )

**Comment by f5cs** [comment]
in corodva:
use cordova-plugin-file read wasm,then call the follow function:
	readBinaryFile:function(fileEntry){
		var me = this;
		fileEntry.file(function (file) {
			var reader = new FileReader();
			reader.onloadend = function(evt) {
                               WebAssembly.instantiate(evt.target.result)
			};

			reader.readAsArrayBuffer(file);

		}, me.onErrorReadFile);
	}
