### ISSUE TITLE
stop workers to use a recorder with another audio source

### ISSUE THREAD

**Issue by stephnicolas** [chris-rudmin/opus-recorder#145]
In order to release an existing Recorder properly, I need a function to stop and release the associated worker
Thank you
Stephane

**Comment by chris-rudmin** [comment]
From the readme.

> rec.stop()
stop will cease capturing audio and disable the monitoring and mic input stream. Will request the recorded data and then terminate the worker once the final data has been published. Will raise the stop event when stopped.
