### ISSUE TITLE
wasm streaming compile failed: TypeError: Response has unsupported MIME type

### ISSUE THREAD

**Issue by IvanDreamer** [chris-rudmin/opus-recorder#147]
Hi all! 

Did someone experience this error? 

`wasm streaming compile failed: TypeError: Response has unsupported MIME type
encoderWorker.min.js:1:20702
falling back to ArrayBuffer instantiation`

Yesterday my code worked, but today it gives me this. :(

EDIT: I see it in Firefox, in Chrome there is just nothing, just does not work without any errors.

EDIT: It's just a warning and the code works (the reason was in other piece of code). But even after in Rails I added MIME type for .wasm it remains the same.

**Comment by chris-rudmin** [comment]
This means your server hosting the wasm files does not serve them using the
correct mime type. It should not break any functionality

**Comment by IvanDreamer** [comment]
@chris-rudmin Thank you for your response! It's true! My bad. Sorry for taking your time.
