### ISSUE TITLE
How to reduce audio output file size

### ISSUE THREAD

**Issue by raghuxseed** [chris-rudmin/opus-recorder#148]
For 1 min recording the audio file size is around 2.5mb, which i have to reduce it to less than 300kb.
I tried to vary the config options but couldnt minimize the size of the audio.

config options for 1 min 2.5mb output are mentioned below
options : {
          monitorGain:0,
          recordingGain:1,
          numberOfChannels:1,
          bitRate:19000,
          encoderSampleRate:48000
} 
Please help with proper config data to reach the audio file size to less than 300kb.
Waiting for the reply
Thanks.

**Comment by chris-rudmin** [comment]
@raghuxseed Hmm, You could try not set `bitRate` and let the encoder select the appropriate bitrate for you. It will select an optimized bitRate. You could also try the following values
```
encoderSampleRate: 8000,
encoderApplication: 2048
```
Also try recording complete silence, the encoder will be able to compress the audio more if the input is less complex.  Good luck

**Comment by raghuxseed** [comment]
thanks for the response, i tried to add those values of encoderSampleRate and encoderApplication as suggested but there is no change in file size , it is still 2.5mb for 1 min.

i have converted wav sample file to opus online by setting some config options **file size resulted is 170kb** without drop in quality of the audio and compared with the recorded file of the current application. On VLC player statics i observed major difference in data for stream bit rate property.

<img width="1014" alt="screen shot 2018-04-15 at 3 57 22 pm" src="https://user-images.githubusercontent.com/19908022/38777499-89fb4d0a-40c6-11e8-82ae-780b725a9d37.png">
<img width="991" alt="screen shot 2018-04-15 at 3 56 59 pm" src="https://user-images.githubusercontent.com/19908022/38777500-8a36905e-40c6-11e8-8df3-4f7a6b5682cc.png">


for stream bit rate  as shown in the screen shots attached, there is a larger difference in the values.
stream bit rate is 354kb/s using the current application recorded file
stream bit rate is 25kb/s for the file converted online from wav to opus.

Please help how can i achieve stream bit rate from 354kb/s to  25kb/s. which config property i need to pass to achieve this.

**Comment by chris-rudmin** [comment]
<img width="1334" alt="screen shot 2018-04-15 at 3 24 13 pm" src="https://user-images.githubusercontent.com/506755/38782425-298004d4-40c1-11e8-879d-f847fac0e059.png">

@raghuxseed I'm not sure what to tell you. Check your settings and try again?  I was able to record 1 minute of audio with those settings with file size 22KB.

**Comment by vaibhavhrt** [comment]
Had same issue , turns out I had to use EncoderWorker not WaveWorker
`encoderPath: "{% static '/js/opus-recorder/encoderWorker.min.js' %}"`
