### ISSUE TITLE
Ability to record in segments

### ISSUE THREAD

**Issue by thekyriarchy** [chris-rudmin/opus-recorder#149]
I am looking to be able to do the following from the microphone: 

Start recording, then either

- save segment and continue recording next
- restart segment
- pause
- review (play back) current recording segment

then, upon final save, have one file that is all of the segments that were saved rather than restarted. is this possible with the current instance methods available?

**Comment by chris-rudmin** [comment]
@thekyriarchy Out of the box, such a use case is not supported. However you could create an implementation that records multiple "segments" and at the end of all the recordings concatenate all the opus files into one file (note that some opus decoder implementations might not support concatenated files)
