### ISSUE TITLE
MIME type Warning from encoderWorker.js in Chrome 66

### ISSUE THREAD

**Issue by ZachMoreno** [chris-rudmin/opus-recorder#151]
Hi Chris, ran into this after updating to Chrome 66 & doesn't seem to be impacting recording in any way

**Chrome Build Info:** Version 66.0.3359.139 (Official Build) (64-bit)

**Warnings:**
wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'. - encoderWorker.min.js:1

falling back to ArrayBuffer instantiation - encoderWorker.min.js:1

**Comment by chris-rudmin** [comment]
@ZachMoreno Thanks for the report.  You can resolve this warning, by serving the wasm file from your server using the MIME type `application/wasm`
