### ISSUE TITLE
severe artifacts when recording WAV and input is 1.0

### ISSUE THREAD

**Issue by belm0** [chris-rudmin/opus-recorder#152]
I'm recording to 16-bit WAV, configured as follows:
```
new Recorder({ numberOfChannels: 1, wavBitDepth: 16, encoderPath: 'waveWorker.js'})
```

I'm clamping my floating-point audio value between -1 and 1 before sending to recorder.  The problem is that when the clipping limit is hit it results in loud pops in the resulting WAV file.  I don't hear the pops when playing the same audio directly to speaker.

Furthermore if I change my clamp to -.999 and .999, the artifacts go away.  It leaves me to believe that the sample limit value 1 isn't being handled properly.  If it's the case that there is some 1-ε requirement, I'd expect the library to clamp to that internally.

Reproduced with 24-bit WAV as well.

**Comment by chris-rudmin** [comment]
The `wavWorker.js` should do hard clipping if the signal is out of bounds.
https://github.com/chris-rudmin/opus-recorder/blob/master/src/waveWorker.js#L61
I haven't actually tested that scenario so there very well could be bugs.

**Comment by belm0** [comment]
The bug can be seen in the lines following that.  The maximum value which can be represented in a signed integer is 2^N-1, yet the code is mapping 1.0 to 2^N.  So e.g. for 16 bit, 1.0-ε is being mapped to 32767, while 1.0 is mapped to -32768, causing huge discontinuities in the output.

Separately, the 8-bit handling (`(sample + 1) * 128`) is suspect.  It should follow the same pattern as the other sample sizes.

**Comment by chris-rudmin** [comment]
@belm0 Thanks for the investigation. I'll put a fix in.

**Comment by belm0** [comment]
Since a signed integer holds a half-open range [-2^M, 2^M), where M = N - 1, the input floating point value should be clamped to half open range [-1, 1), i.e. -1 <= v <= 1-ε.   In JS Number.EPSILON is available for this clamping.  Then the conversion by `value * 2^M` can be left as-is (except for the buggy 8-bit case).
