### ISSUE TITLE
Recorder not working in iOS Safari Home Web App (Standalone mode)

### ISSUE THREAD

**Issue by ohbiko** [chris-rudmin/opus-recorder#159]
Hi there,

The recorder constructor errors out when the website (web app) is saved to the Home screen and launched from there.  Do you know of any workarounds?

Thanks!

**Comment by chris-rudmin** [comment]
@ohbiko I was unable to reproduce the issue using iOS 11.4 and the example encoder. Could you provide a sample which reproduces the issue?

**Comment by ohbiko** [comment]
@chris-rudmin You need to have the link open fullscreen as a standalone web app.  Add the following to the `<head>` of your example and you should be able to reproduce it.

Recorder.isRecordingSupported() will return `true`.

```
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-touch-fullscreen" content="yes">
```

**Comment by chris-rudmin** [comment]
I could not find any official documentation about `apple-touch-fullscreen`
meta tag. Does the issue occur if you remove this meta tag?

**Comment by chris-rudmin** [comment]
It would be useful if you could add the console output with any relevant
errors here.

**Comment by ohbiko** [comment]
Basically these tags are for standalone web apps.  When these tags are in the head and the page is added to the home screen, tapping the app icon that’s now in the home screen will open the app in a standalone view (not Safari) that’s similar to a native app.  When in standalone mode, the recorder doesn’t work.

Yes removing these tags fixes the issue but the web app experience is gone since the app will open in Safari.

**Comment by rotem925** [comment]
I think this happens cause there is no support for WebWorker on web views.

This why I compiled the worker as asmjs.

**Comment by chris-rudmin** [comment]
@ohbiko My point about the undocumented tag `apple-touch-fullscreen` is that it doesn't make sense to me to support undocumented features. If the features is documented and supported by apple, then it might be worthwhile to debug the problem and add support.
