### ISSUE TITLE
The Web Audio autoplay policy will be re-enabled in Chrome 70 (October 2018)

### ISSUE THREAD

**Issue by michael-ecb** [chris-rudmin/opus-recorder#162]
Hi ,

we are getting this warning :
"The Web Audio autoplay policy will be re-enabled in Chrome 70 (October 2018)"
can be simply reproduced on your waveRecorder.html example.

it's look we have to deal with resume or init AudioContext only on user interaction.

Thanks.

**Comment by chris-rudmin** [comment]
Thanks for the bug report @michael-ecb . I will take a look.

**Comment by michael-ecb** [comment]
@chris-rudmin  thanks chris!

**Comment by michael-ecb** [comment]
hi @chris-rudmin  do you think it will be fixed soon ?

thanks

**Comment by chris-rudmin** [comment]
I haven't prioritized this, because I'm not sure there is a bug.  The AudioContext we create is created on `start` which should be from a user interaction.

**Comment by michael-ecb** [comment]
its also happen on the recorder example so for sure it will make block us to record in Octobre  :/

**Comment by michael-ecb** [comment]
hi @chris-rudmin  ,  thanks you for your help, 
I download the v 5.0.0  and checked in encoder.html , but the warning stay here...

**Comment by chris-rudmin** [comment]
@michael-ecb Yes, the warning exists for any page using the `audioContext`.  Even if you check the fixed airhorn (from the link in page from the warning) you will continue to see the warning.
