### ISSUE TITLE
Wrong path to encoderWorker.min.js 

### ISSUE THREAD

**Issue by gadzhimari** [chris-rudmin/opus-recorder#164]
I've read docs and it's says that encoderPath is optional parameter. If so, why I get the following error when I try to initialize the Record instance:
```GET http://localhost:3000/encoderWorker.min.js 404 (Not Found)```

I've install version 5.0.0 as dependency in my react project. The question is if this package shipped with all necessary code, why should copy and paste inside my project additional worker file? I thought, if I use third-party library and install it, I don't need copy and paste and create another folder inside project just do it work well. 

Let me explain more concrete. Imagine we have core project which depends on other components library. This is just two separate project. Inside components library I have a Recorder component that use this opus-recorder lib. Why should I copy this encoderWorker.min.js and put it inside core project?

Here the screenshot which show that everything already had inside folder /node_module/opus-recorder

![2018-10-11_17-38-24](https://user-images.githubusercontent.com/1849608/46817967-c1795200-cd88-11e8-94ad-d7d15e649d20.png)

**Comment by chris-rudmin** [comment]
It should probably read that the worker path is optional if the files are hosted in the root.  If you are building the project in a node environment, you might be able to specify the absolute path to the worker relative to recorderjs using `path.resolve(__dirname, 'encoderWorker.min.js')`  If you have some suggestions on how we can handle this better, I would be glad to make those changes.

**Comment by chris-rudmin** [comment]
Even though I have published this in npm, it is a package which is built for the browser, and it will not work in node.

**Comment by gadzhimari** [comment]
Yes I'm using node project. Is there any way just to get path from node_module folder. I just want the recorder.js get content from encoderWorker.js, because they sits both on the same location.

**Comment by gadzhimari** [comment]
I've add this line ```encoderPath: path.resolve(__dirname, 'encoderWorker.min.js')``` nothing is changed.

**Comment by chris-rudmin** [comment]
@gadzhimari It's not an easy fix, because the workers are loaded at runtime in the browser, their paths are relative to the page hosting the recorder and not relative to the recorder.js file. I am investigating rolling up the libraries using webpack worker-loader to see if it can help.

**Comment by gadzhimari** [comment]
Any progress?

**Comment by chris-rudmin** [comment]
I tried, but had no success.  I haven't had time to look at it more in
depth.

**Comment by gadzhimari** [comment]
Could explain me more deeply about the main reason that couldn't be resolved. I don't see the whole picture that caused the problem. I've just want don't specify any path to encoder file and the library by default link to itself inside `node_module/opus-recorder/`

**Comment by chris-rudmin** [comment]
opus-recorder depends on statically hosted files to complete its work.  1.
It will try to instantiate a webworker instance using a relative path to
encoderWorker.min.js and 2. encoderWorker.min.js will do a streaming
compile of encoderWorker.min.wasm.  Currently I'm using webpack to rollup
the js, and it should support webworkers, however the webpack rollup fails
when trying to include the emscripten content as it is trying to support
multiple environments (node and web).  This is as far as I got.  Since
webassembly is a bleeding edge feature, there is not really any support for
rolling up emscripten and wasm content. I have seen some stackoverflow
posts where people have had success, but I was not able to replicate that
success.

**Comment by gadzhimari** [comment]
I'm currently solve half a problem, by encoding `encoderWorker.min.js` as a base64 string in my prod environment using webpack url-loader. But then I try to start recording I got this error:
![error](https://user-images.githubusercontent.com/1849608/49330641-5f77e480-f5a2-11e8-9933-2a594646953d.png)

I tried to convert the wasm file as base64 string, but this is not solve my issue. Maybe I do something wrong.

**Comment by chris-rudmin** [comment]
@MedElfadhelELHACHEMI I don't have a quick fix for this unfortunately.  I have some ideas how it could be done, but it will require a significant change in architecture.

**Comment by LavaRiddle** [comment]
@MedElfadhelELHACHEMI Are you using webpack with your React application?

You can use 'CopyWebpackPlugin' to move the file to your projects root directory rather than calling from node_modules.

```  
new CopyWebpackPlugin([  {
      from: 
         path.resolve(
            __dirname,
            '../node_modules/opus-recorder/dist/encoderWorker.min.js'
          ),
      to: './'
}])
```
Hope that helps?
