### ISSUE TITLE
Compatibility with Firefox < 53

### ISSUE THREAD

**Issue by baptiste-pipplet** [chris-rudmin/opus-recorder#175]
Hi,

First thanks for this great library, this has helped us a lot!
We are however dealing with people with old versions of Firefox, < 53.

I understand that Opus recorder only supports Firefox >= 53. 
But I was wondering, is there is a major issue that forbids it to work with earlier versions?

We use adapter.js and thought that it should handle the getUserMedia deprecation pretty well.  

We will have a look on our side but if you have any info on how it would / would not work with earlier versions we would appreciate the help.

Have a great day

Baptiste

**Comment by chris-rudmin** [comment]
@baptiste-pipplet I have not tested this library with older versions of browsers. If you wish to provide a more detailed compatibility chart, I could include it in the readme.

The main feature we use which would limit backwards compatibility is probably WebAssembly support.
