### ISSUE TITLE
audio seems skipped and choppy

### ISSUE THREAD

**Issue by z-sanjivini** [chris-rudmin/opus-recorder#176]
Tried implementing the code. But when running on a windows 10 machine the audio seems to be choppy at points. I also tried monitoring the CPU utilisation and it went from 18% when running the application to 36% at maximum.

**Comment by chris-rudmin** [comment]
@SanjiviniAhuja  I might be able to provide a reasonable hypothesis if I can know what  Browser, OS, Machine specs, Sample Rate, Recording length and Recording configuration can reliably reproduce the issue.

**Comment by SanjiviniAhuja** [comment]
I am not able to reproduce the issue every time, so I'm not sure how successful you might be in that attempt but I'm using
Firefox 63.0 Chrome 70.0
Windows 10, 8GB Ram, 2.6GHz
Sample Rate and other Audio related specs are the same as given in the sample.

**Comment by chris-rudmin** [comment]
My guess would be that your audio dropouts are related to our use of `scriptProcessorNode` which uses the main thread to pass audio buffers to the encoder. If your webpage has some code running in the main thread, it could result in blocking/delaying the event loop for processing the audio buffers which could result in dropped audio.
