### ISSUE TITLE
Memory Access out of bounds

### ISSUE THREAD

**Issue by JackBilesAmmi** [chris-rudmin/opus-recorder#178]
<img width="871" alt="screenshot 2018-12-11 at 13 25 32" src="https://user-images.githubusercontent.com/36856350/49803639-44e2ff80-fd48-11e8-9d1f-0562726dd64d.png">

Hi! A couple of months ago this repo worked great without any warnings or errors. I've recently come back to the same code and the following errors and warnings have appeared in Google Chrome Version 71.0.3578.80 (Official Build) (64-bit).

I sadly have no experience of EMSCRIPT or any kind of Web Assembly languages so i've brought a problem without a solution (Which i don't normally do)! Any further advice of possible fixes?

**Comment by chris-rudmin** [comment]
Are you configuring either `encoderComplexity` or `encoderBitRate`? and what are the values you are trying to set?

**Comment by JackBilesAmmi** [comment]
Hi Chris,

From your prompts given here it appears `encoderComplexity` was throwing the error. I have removed and all is working fine now.

```
var options = {
  bufferLength: analyser.fftSize,
  numberOfChannels: 1,
  encoderComplexity: 5,
  encoderApplication: 2048,
  encoderSampleRate: context.sampleRate,
  encoderPath: "./JS/dist/encoderWorker.min.js"
};
```

These were the original values.

**Comment by chris-rudmin** [comment]
@JackBilesAmmi I added encoderComplexity to the example page to validate that it works. I didn't encounter any out of bounds errors. Closing.
