### ISSUE TITLE
noise reduction

### ISSUE THREAD

**Issue by samanmohamadi** [chris-rudmin/opus-recorder#179]
Hi, @chris-rudmin  Thanks for your great work.
Do you have any idea  about noise reduction?

**Comment by chris-rudmin** [comment]
Yeah, lots of different techniques to reduce noise. What kind of noise are you dealing with?

**Comment by chris-rudmin** [comment]
For background noise, you will probably get best results with hardware noise suppression.  Try enabling the flag for the audio stream: https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSettings/noiseSuppression.  If you are recording just voice, you can specify that in `encoderApplication`, which will then bandpass your audio to eliminate non voice frequencies.
