### ISSUE TITLE
loadWorker takes time to load

### ISSUE THREAD

**Issue by rotem925** [chris-rudmin/opus-recorder#181]
It seems that it takes too much time to load the worker.
I moved from version 5.0 to the latest.
The previous version was loading the worker pretty fast, now it just hangs for a few when loading the worker.

It seems like the "ready" event from the worker takes time to trigger.
On slower devices, this is very noticeable. I tried it on Nexus 5x, Samsung Galaxy Tab 3, and Sony Xperia tablet (all with the latest Android version).

To reproduce it, just add a console.log on the callback event from the worker(switch case,'ready')

Thanks

**Comment by chris-rudmin** [comment]
I believe what is happening is that we changed the behaviour so that the
start callback is only being called one the worker is ready to receive
buffers. Previously we were calling back earlier and buffering the data to
send to the worker. The time to start the worker should be the same, but
with the new logic, it should reduce streaming latency for those who want
low latency streaming.

**Comment by rotem925** [comment]
I'm not seeing what you describe..
I'm loosing the buffers at the beginning of the recording. This is how I
noticed the issue. I think you should still hold the buffer as soon as the
recording starts, and send to the worker when it is ready, I'm not seeing
this happening.

The behavior now is that you have to wait about two seconds after pressing
the record button in order to not lose the speech recording(we do voice
recognition) .

I almost sure you ignore the first buffers that comes from the browser..

I currently rolled back to the previous version, but I think that really an
issue..

Thank you!

**Comment by chris-rudmin** [comment]
That is correct. We are now discarding buffers until the worker is ready to record to reduce the steaming latency. We could revert to the v5 behaviour for non streaming usage.

**Comment by rotem925** [comment]
@chris-rudmin What do you mean non streaming usage? streamPages=false?
Actually I think that should be as v5 behaviour for both stream and non stream.
I think when you start the recording, there shouldn't be a requirement to wait till the worker is ready.
I think you should just keep the buffer aside till the worker is ready.

I use the streamPages=true option. discarding buffer will mean there is no option to use the stream option at all.

I realy think you need V5 behaviour for both streaming and non streaming option.
Maybe another solution will be to add an option like: 
_discardBuffersUnillWorkerReady:false_
I think **false** should be the default. That will allow the developer to decide..

Thanks!

**Comment by chris-rudmin** [comment]
@rotem925 Good suggestion. I'll put a fix in.
