### ISSUE TITLE
opus-recorder with ios 12

### ISSUE THREAD

**Issue by echoTab** [chris-rudmin/opus-recorder#182]
I have the waveRecorder example working fine with Chrome, msEdge, and Firefox. However Safari on my iPhone 12.1.2 I get an error "request not allowed" upon recorder.start(). Is this a known issue with IOS 12, or  is there something I need to do to make it work?

**Comment by chris-rudmin** [comment]
Yes it is a known issue. See the known issues in the readme.

**Comment by chris-rudmin** [comment]
I think support was added in 12.2.0 but I don't recall exactly. I don't
think iOS 11 was working ever with webassembly.

**Comment by chris-rudmin** [comment]
@echoTab I think I misunderstood your error.  I believe you would receive a "Request Not Allowed" error when you try to record audio over http, or if the action was not initiated by the user. Audio recording require pages served over https, and that the start needs to be initiated by a user input. This is documented in the README.
