### ISSUE TITLE
Include version number

### ISSUE THREAD

**Issue by thijstriemstra** [chris-rudmin/opus-recorder#183]
Would be nice to have a version nr. It helps debugging when users report an issue.

**Comment by chris-rudmin** [comment]
I agree it would be nice. I generally just test against the latest releases
of browsers. I’m not prepared to regression test older versions for each
change I make.

**Comment by thijstriemstra** [comment]
Cool. I'd like to print it in the console, like the other libraries, e.g. https://collab-project.github.io/videojs-record/examples/audio-only-opus.html
