### ISSUE TITLE
It is not working on iOS 12.1.2 Chrome

### ISSUE THREAD

**Issue by nasief** [chris-rudmin/opus-recorder#186]
When trying to check `Recorder.isRecordingSupported` on Chrome on iOS 12.1.2, it returns `false`. Is it not supported? could be something done about it?

**Comment by chris-rudmin** [comment]
I don’t have time to investigate at the moment. Feel free to make a pull request if you find the issue.

**Comment by chris-rudmin** [comment]
Unfortunately I don't have 12.1.2 installed anywhere to test.  12.1.4 does not seem to have any issues.

**Comment by nasief** [comment]
Thanks for looking into this. I might be investigating this sometime later. If things go smooth, I will open a PR for you.
