### ISSUE TITLE
More a Question than an issue (Example Folder)

### ISSUE THREAD

**Issue by Grewis** [chris-rudmin/opus-recorder#187]
Hi !
Is the example in the example folder works ? I have tried to open them in a browser but with the encoder when I press start it ask permission to use my mic, I say yes but then nothing happend and I can only press the start Button.

**Comment by chris-rudmin** [comment]
the [encoder.html](https://raw.githack.com/chris-rudmin/opus-recorder/master/example/encoder.html) example is working for me in chrome v73.
