### ISSUE TITLE
Produce PCM buffers only

### ISSUE THREAD

**Issue by binarykitchen** [chris-rudmin/opus-recorder#190]
Would be good to add a new config which gives me PCM buffers only without WAV generation. This for an app of mine where WAV is rather generated on server side.

So, I'm only after PCM data. Would it be too much to ask for this?

**Comment by chris-rudmin** [comment]
You don't need a lib to access PCM buffers: https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API. Connect to a stream and access raw buffers directly.

**Comment by binarykitchen** [comment]
Sure could pipe that although it's not already threaded in workers like in your package.
