### ISSUE TITLE
44.1kHz opus encoding instead of 48kHz

### ISSUE THREAD

**Issue by akalmykov** [chris-rudmin/opus-recorder#191]
Hi, 

First of all, thank you for this recorder.

I have one question. There was an question about WAV encoding that is always 44.1kHz. You have mentioned that "The resampler works quite well if recording to ogg opus".  But I have encountered similar problem with Opus encoder. It seems that despite the default setting of 48kHz sampling rate, as in this example

![image](https://user-images.githubusercontent.com/4420479/60842911-f6161f00-a1dd-11e9-9449-ff74d5576a77.png)

I always get 44.1kHz sample rate. Below is the output of opusinfo command from opus-tools for a recorded file:

```
$ opusinfo 2019-07-08T21_07_40.995Z.opus 

Processing file "2019-07-08T21_07_40.995Z.opus"...

New logical stream (#1, serial: afd996f0): type opus
Encoded with RecorderJS
Opus stream 1:
	Pre-skip: 3840
	Playback gain: 0 dB
	Channels: 1
	Original sample rate: 44100Hz
	Packet duration:   20.0ms (max),   20.0ms (avg),   20.0ms (min)
	Page duration:    800.0ms (max),  760.0ms (avg),  640.0ms (min)
	Total data length: 19635 bytes (overhead: 1.84%)
	Playback length: 0m:02.960s
	Average bitrate: 53.07 kb/s, w/o overhead: 52.09 kb/s
Logical stream 1 ended

```
Do I miss something (may be "original sample rate" is not the same as "encoder sample rate") or is it indeed 44.1kHz recording? Can I fix this somehow? Unfortunately, I need to have 48kHz files for Google Speech API as it does not support 44.1kHz opus.

Thanks in advance!

**Comment by chris-rudmin** [comment]
Original sample rate is the sample rate of your original audio. To get
48000 hz sample rate You should change your audio input device sample rate
and restart your browser.

**Comment by akalmykov** [comment]
So opus-recorder ignores encoderSampleRate parameter, doesn't perform resampling to 48 khZ during encoding and preserves original sample rate?

**Comment by akalmykov** [comment]
Ok, so Original sample rate has nothing to do with encoderSampleRate parameter. 
Do you know how can I check the actual sample rate of the recorded file?
_opusinfo_ does not provide such information and I still suspect that there might be something wrong with the sample rate

**Comment by chris-rudmin** [comment]
The input sample rate field is defined in the [spec](https://tools.ietf.org/id/draft-ietf-codec-oggopus-02.html). Ogg Opus does not store the encoding sample rate in the meta data (internally everything is processed at 48khz). An encoded Ogg Opus file does not have a sample rate, but instead an encoded but a bit rate.  The algorithm to determine the playback sample rate algorithm is defined in the spec as well.

If you read the readme. There is an option to force the input sample rate field to an arbitrary value to support google speech API. They incorrectly interpret this field when processing the audio. I have opened a bug with them about a year ago (no action taken yet)

**Comment by akalmykov** [comment]
Thanks! It worked. Just for the reference of those who might read this thread later: the option is **originalSampleRateOverride**
