### ISSUE TITLE
[Question] Which OGG Opus config options for Google Speech API?

### ISSUE THREAD

**Issue by femt0** [chris-rudmin/opus-recorder#193]
Hi,
First of all, thank you for this amazing library!
I'm using it to stream OGG Opus audio to the Google Speech API but I'm not getting text back.
Here are my options:
``` javascript
var options = {
    monitorGain: 0,
    recordingGain: 1,
    numberOfChannels: 1,
    encoderSampleRate: 16000,
    encoderPath: "./javascript/ogg_opus/encoderWorker.min.js",
    originalSampleRateOverride: 16000,
    streamPages: true,
    encoderApplication: 2048
};
```
Do you know what could be wrong with these options?
Thanks in advance!

**Comment by chris-rudmin** [comment]
Those options look alright. I’m not familiar with the google streaming API,
so I’m not sure i can help. Can you point me to some doc of the API you are
using?

**Comment by unimatrix099** [comment]
if the API is set to AudioEncoding.OGG and you send OGG data you will not get anything, by mistake I found that if you set to AudioEncoding.MP3 and send OGG audio data it will work... :)
