### ISSUE TITLE
state stays inactive on start

### ISSUE THREAD

**Issue by flieks** [chris-rudmin/opus-recorder#194]
Testing in windows 10 opera.
State stays inactive on recorder.start()
I am providing no options to new Recorder()
![image](https://user-images.githubusercontent.com/5032389/71492861-d5e52580-283a-11ea-8695-529e3df4ebfd.png)
ondataavailable is never hit

**Comment by chris-rudmin** [comment]
I haven't tested opera since they switched to WebKit.  Can you please specify the version you are testing on?

**Comment by flieks** [comment]
Version is 65.0.3467.78
Isnt opera using chromium ?

**Comment by chris-rudmin** [comment]
Yea I meant chromium. Last time I tested opera was v44

**Comment by chris-rudmin** [comment]
@flieks I just did a test on Opera v65 and recorder worked without issues. Can you please post the error message that you encounter?

**Comment by flieks** [comment]
thanks
i do sth like this (no error but it never goes inside the on

``` 
    var Recorder = require('opus-recorder');
    var rec = new Recorder();

    rec.ondataavailable = function( typedArray ){
       var dataBlob = new Blob( [typedArray], { type: 'audio/ogg' } );
       setLinkBlob(window.URL.createObjectURL(dataBlob))
    
        )
    };

    rec.start();
```
using react

**Comment by chris-rudmin** [comment]
Yeah, I don’t think you can do ´require(opus-recorder)´ as it requires a
statically hosted wasm file. Check if you are getting network errors 404
maybe.

**Comment by flieks** [comment]
i am not getting a 404. Recorder is properly initialized and it can be started but it never goes in onDataAvailable.. Maybe because on chromium, ogg containers arent supported and we have to use webm ?
Problem is i need ogg

**Comment by chris-rudmin** [comment]
The example encoder works fine in Opera for me. I don't think I can help you debug your application any further unless you can provide me an example which reproduces the issue.
