### ISSUE TITLE
[Question] Mission critical audio recording (recording indicator & periodic saving)

### ISSUE THREAD

**Issue by radulle** [chris-rudmin/opus-recorder#195]
@chris-rudmin I apologize since this is not an issue but I didn't know how best to approach you.

In your opinion what would be the best strategy for making sure recording is being conducted and that it is saved for example every couple of seconds to IndexedDB and filesystem without interrupting UI/UX? I want to be sure that if user for some reason kills the browser or there is a crash that audio is safe on user's storage.

**Comment by chris-rudmin** [comment]
Safest way would be to stream it to your server as it is being recorded

**Comment by radulle** [comment]
Thank you, but due to the nature of the app that won't be possible.
If you have a minute for a few more questions it would be greatly appreciated:
1. Do pause/resume also has to be called from user initiated events in Safari and would it be possible to have ondataavailable event available onpause or is reuseWorker with start/stop only solution.
2. How do you use give an example of streamPages usage?
3. If CDN is used to load the recorder.min.js how do you do same for worker js and wasm files?

**Comment by chris-rudmin** [comment]
1. I don't believe those actions need to be user initiated, but you are best to test and see.
2. I don't have an example.  It works the same as without streamPages, but you will get individual ogg pages as they are ready.
3. I've never tried with a CDN. Let me know if you get it working.
