### ISSUE TITLE
Paid feature request: add onVolumeChanged hook

### ISSUE THREAD

**Issue by zabaat** [chris-rudmin/opus-recorder#196]
Thanks for this awesome work Chris, would you be open to adding onVolumeChanged hook to your library?
We are using this for a client project and would be happy to compensate you for your work.
Please reply if you are interested. Thanks!

**Comment by chris-rudmin** [comment]
Thanks. I am not quite sure what feature you are asking for. This is a
library for recording audio, and thus there is no volume to control. Are
you referring to recording gain?

Oggopus playback and playback volume would usually be handled by the
browser.

**Comment by trevordilley** [comment]
@chris-rudmin Hi, I work with @zabaat . We mean the volume of the voice being recorded. So as you speak into the Mic we'd like to be able to see a volume bar go up and down. 

For example Twilio exposes a `volume` event that you can then leverage in React like this:

```
        Twilio.Device.on("connect", (conn: any) => {
           
            // inVol is the "Volume" of the voice
            conn.volume((inVol: number) => {
                this.setState({currentVolume: inVol})
            })
        })
```

Does that make sense?

**Comment by trevordilley** [comment]
Oh and to be clear, we're asking (and willing to compensate for!) simply adding a callback similar to the conn.volume() in the example above, sort of how you have an onstart(), onpause(), etc. If there were an onvolume() that could be assigned to a function expecting a number value, that would be great. We of course are the ones making the react app with the volume bar visualization!

**Comment by chris-rudmin** [comment]
@trevordilley If I understand correctly, you want to create a visualization of the microphone SPL.  Something like this? https://webaudiodemos.appspot.com/volume-meter/
