### ISSUE TITLE
[Question] How to play each frame correctly?

### ISSUE THREAD

**Issue by lihengx** [chris-rudmin/opus-recorder#197]
I want to use opus recorder for a realtime voice chat app.
I set streamPages = true, so dataAvailable callback function always output some frame blob, but these blob seems corrupted because I couldn't play it directly.
Could you please help me?

**Comment by chris-rudmin** [comment]
@lihengx OGG opus pages are not meant to be played individually, but as part of a stream. You will need to send the pages to your server and then make it available as a stream for playback.
