### ISSUE TITLE
FileEncoder example generates invalid ogg file?

### ISSUE THREAD

**Issue by ikqaGarbage** [chris-rudmin/opus-recorder#199]
I'm trying to run the FileEncoder example on chrome 82 but I can't seem to get it working. Was the api changed without updating the examples?

it seems like now the worker is returning the encoded data in data.page instead of in the main data object.

**Comment by chris-rudmin** [comment]
It is quite possible. I haven’t been maintaining this example page. If you
find the problem, send me a pull request.
