### ISSUE TITLE
Should provide a License

### ISSUE THREAD

**Issue by lafferty** [chris-rudmin/opus-recorder#2]
The project provides license details for the source it reuses; however, there doesn't seem to be a license for project itself.  You'd expect a copyright notice with the author's name to cover the updates.

**Comment by chris-rudmin** [comment]
It's Licensed under MIT license as is the original. It's in the readme.

**Comment by TxAg12** [comment]
I was reviewing the license file, and I did not find anything specifically for your fork Chris. Have you considered adding a MIT (or whatever you prefer) to the license file, something like:

Opus-Recorder License (MIT)
Copyright 2018 Chris Rudmin.
MIT license text...

It is unclear if it is your intent to offer your code (everything that is inherently your copyright) as MIT. The license file essentially is covering your liability for using open source code of others, but users of Opus-Recorder source code don't have a license for your project.

I am not an expert in licensing; however, I want to give credit where credit is due and I do not want to infringe on your copyright.

**Comment by chris-rudmin** [comment]
@TxAg12 I left the license the same as created by Matt Diamond. My code is a fork of his repository. Why would I need to add an additional license?

**Comment by TxAg12** [comment]
For you personally, you met the requirements of the other open source code by including the applicable licenses.

However, for the rest of us, there is no license for this specific software. As I understand it, you now own the copyright to _your work, whether or not you actually say "Copyright blah..." So it's basically "unlicensed" unless you provide a license that allows it to be open source, for use by others.

I think your intention is to make your repository MIT (correct me if I am incorrect). However, you cannot shift the liability to Matt Diamond by saying it's under his license (which is discussed in the license text). Opus Recorder is yours. Not his (even if much of it is his code). So I think the best way is to make clear your copyright and that you are choosing to also license it as MIT.

Here are some links that might be useful:

https://softwareengineering.stackexchange.com/a/222364

https://softwareengineering.stackexchange.com/questions/277688/if-i-fork-a-project-on-github-that-is-licensed-under-mit-how-to-i-handle-the-at

**Comment by chris-rudmin** [comment]
Thanks for the information. I will review it and see about updating the license correctly.
