### ISSUE TITLE
ondataavailable only called after stopping the Recorder

### ISSUE THREAD

**Issue by stefan-falk** [chris-rudmin/opus-recorder#200]
I am tring to integrate the `Recorder` following [this example](https://github.com/chris-rudmin/opus-recorder/blob/master/example/waveRecorder.html).

It seems to work so far except that I do not get data chunks once they're available but only after I `stop()` the recorder.

With the basic `MediaRecorder`  we can e.g. set the milliseconds but how can I do that with the opus `Recorder`?

I tried setting `streamPages` but it did not have the desired effect.

This is currently what I am at:

```javascript
var options = {
    monitorGain: 0,
    recordingGain: 1,
    numberOfChannels: 1,
    encoderSampleRate: 16000,
    originalSampleRateOverride: 16000,
    encoderPath: 'js/waveWorker.min.js',
    streamPages: true,
    maxFramesPerPage: 1,
    encoderFrameSize: 1
};

mediaRecorder = new Recorder(options);
mediaRecorder.ondataavailable = typedArray => {
    console.log(typedArray);
    const dataBlob = new Blob(typedArray, { type: mimeType });
    chunks.push(dataBlob);
};
````

**Comment by chris-rudmin** [comment]
Wave files are not streamable because the header at the beginning needs to
specify the entire length of the recording.

**Comment by chris-rudmin** [comment]
Please refer to the readme for supported config options when recording wav.

**Comment by stefan-falk** [comment]
@chris-rudmin Yes, but I was thinking about doing it like I would do it with the default `MediaRecorder`. With it one just can do this:

```javascript
    mediaRecorder.start(100);

    sttInterval = setInterval(() => {
        const dataBlob = chunks.splice(0, chunks.length);
        const blob = new Blob(dataBlob, {'type': 'audio/wav'});
        const fileReader = new FileReader();
        fileReader.onload = function () {
            const buffer = this.result;
            sttSocket.emit('record', buffer);
        };
        fileReader.readAsArrayBuffer(blob);
    }, intervalTimeout);
```

I was hoping something like this would be possible.

**Comment by chris-rudmin** [comment]
@stefan-falk I see. This is currently not possible with this library.
