### ISSUE TITLE
Update from deprecated API:  AudioContext.createScriptProcessor() 

### ISSUE THREAD

**Issue by trevordilley** [chris-rudmin/opus-recorder#205]
Hi Chris, we have a client who would like switch over to your recorder as their main recording tool. The one snag is they're uncomfortable that the recorder uses this:
https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/createScriptProcessor

Which appears to be deprecated? Currently they're using the Twilio but would like to use something simpler (they just need to record a single voice recording and upload it to their servers, so Twilio is kinda overkill)

We know this would be a non-trivial effort and would be happy to follow up and discussing bidding it out. You can contact me directly at trevor@twentyideas.com if you want to talk more!

**Comment by trevordilley** [comment]
Specifically here: 
https://github.com/chris-rudmin/opus-recorder/blob/f3fe542f21856c05a739a1bd41b4303f0d0b373b/src/recorder.js#L101

**Comment by chris-rudmin** [comment]
@trevordilley deprecating createScriptProcessor() sound reasonable. Just FYI for your client, that making this change will require dropping support for iOS and Safari on mac.

**Comment by weepy** [comment]
"dropping support for iOS and Safari " seems a shame since they are the main reasons this exists!
