### ISSUE TITLE
High CPU usage when encoding

### ISSUE THREAD

**Issue by adambailey-** [chris-rudmin/opus-recorder#206]
I've yet to track down the root cause in code, but perhaps you'll have better luck than me!

The high CPU usage can be seen by running the [encoder.html example](https://github.com/chris-rudmin/opus-recorder/blob/master/example/encoder.html).

Here is the activity monitor at idle:
![Idle](https://user-images.githubusercontent.com/10304518/82922550-5bcae100-9f3f-11ea-8a56-e64a0e49c109.png)

Recording:
![Recording](https://user-images.githubusercontent.com/10304518/82922575-62f1ef00-9f3f-11ea-81c8-e1164ef564c2.png)

I'm fairly confident that the high CPU usage comes from the encoding, not the recording. My project (closed source, sorry) only uses the encoding part of this repository, and has this same issue.

I'm going to continue looking into this, but hopefully you'll (@chris-rudmin) will be able to get some eyes on this as well to help me out :)

**Comment by chris-rudmin** [comment]
What kind of CPU are you running on? On my machine, CPU usage does not
exceed 8%. In chrome debugger tools, can you record a performance profile
and post the results here?

**Comment by chris-rudmin** [comment]
Can you specify the version of chrome as well? Thanks

**Comment by adambailey-** [comment]
My apologies, I thought I was running the example on this repository, but in fact I was running it on my own fork, which has some additions to the code to stream opus packets without ogg. The high CPU usage occurs on my fork, and not this repository, so I'll go ahead and close this issue.
