### ISSUE TITLE
decoder example not working

### ISSUE THREAD

**Issue by weepy** [chris-rudmin/opus-recorder#207]
Hiya - I was trying to get the decoder example working, but when I click "XHRRequest" button I can see it downloads mono.opus, but gives 3 empty wav files. 
Am I doing something wrong ?

**Comment by chris-rudmin** [comment]
Can you share the file with me?

**Comment by weepy** [comment]
It's just ```mono.opus``` in the example directory. I ran decoder.html and clicked ```Load using XMLHttpRequest```

**Comment by chris-rudmin** [comment]
I see what you mean. I'll have to investigate some more.

**Comment by weepy** [comment]
Great that works now for the mono.opus 
However it doesn't work for this opus that was recorded using the MediaRecorder in Chrome. 

https://drive.google.com/file/d/1mx0jq-7-D4j2jMORsPjmkQEHEufp_dvz/view?usp=sharing

It's possible that it doesn't work because it doesn't have a length ?

**Comment by chris-rudmin** [comment]
It's not using a valid ogg container. You can verify using opus-tools.

**Comment by chris-rudmin** [comment]
I think chrome uses a WebM container by default.
