### ISSUE TITLE
iOS: Waveform analyzer is broken during recording

### ISSUE THREAD

**Issue by Ajaxy** [chris-rudmin/opus-recorder#210]
Hey, thanks for the great module.

I have a problem with iOS 13. I'm using this code which prints out an updating waveform data when the mic is captured:

```js
  const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
  const audioCtx = new (window.AudioContext || window.webkitAudioContext)();
  const source = audioCtx.createMediaStreamSource(stream);
  const analyser = audioCtx.createAnalyser();
  analyser.fftSize = 2048;
  const bufferLength = analyser.frequencyBinCount;
  const dataArray = new Uint8Array(bufferLength);
  source.connect(analyser);

  function tick() {
    analyser.getByteTimeDomainData(dataArray);
    // Logging waveform here:
    console.log(dataArray);
    requestAnimationFrame(tick);
  }

  tick();
```

But once I add this:

```js
  const mediaRecorder = new OpusRecorder();
  await mediaRecorder.start(stream);
```

The console starts producing almost constant values: (127, 128, 129) which are not related to the mic input.

I tried using `stream.clone()` but that did not help. Any suggestions?

It works fine on all other platforms.

**Comment by chris-rudmin** [comment]
start() is expecting an instance of `MediaStreamAudioSourceNode`. You seem to be passing it an instance of `MediaStream`.

**Comment by Ajaxy** [comment]
Thank you, using the same `AudioContext` and `MediaStreamAudioSourceNode` helped!
