### ISSUE TITLE
Can't play file procedurally saved recording 

### ISSUE THREAD

**Issue by ginhinio** [chris-rudmin/opus-recorder#211]
I've been looking at the examples for a few hours now without any luck finding out what I am doing wrong. I am currently recording with StreamPages set to true and sending immediately to the server to be appended to a Writestream. when I press play I get an error telling me it's a corrupted file. Am I doing something wrong?

**Comment by chris-rudmin** [comment]
When you play your writeStream, are you sure you are getting the header packets? If when you press play, you start in a middle of a stream, you will need to make sure to send the header packets first.

**Comment by ginhinio** [comment]
I was just reading about the opus header and checked the file in textformat. it seems like I am not getting the first header only the second one?
```
OggS          ïaF!   ±i?ÃOpusTags
   RecorderJS    OggS   –      ïaF!   ·Ööæ(xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxOggS   ,     ïaF!   ®ý
a(xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxOggS   Â     ïaF!   š’(xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxOggS   X     ïaF!   Wj6(xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxOggS   î     ïaF!   ©¼(xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxOggS   „     ïaF!   ‘ª++(xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxOggS        ïaF!   ÿ
=à(xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxOggS   °     ïaF!	   ¥EOà(xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxOggS   F     ïaF!
   —4Cl(xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxOggS   Ü     ïaF!   %4–(xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

**Comment by chris-rudmin** [comment]
@ginhinio Unless you can provide me a sample which reproduces a bug, I'm not sure I can help you. I'm definitely not equipped to help you debug your server side code.

**Comment by ginhinio** [comment]
> @ginhinio Unless you can provide me an example which reproduces a bug, I'm not sure I can help you. I'm definitely not equipped to help you debug your server side code.

It's okay. I don't think it's something wrong with my backend code as it's tested with an mp3 encoder. I think it's on the client side maybe there some timing issues at the beginning of the ondataavailable function. I'll figure it out and update this thread. Thanks for this project mate! :D
