### ISSUE TITLE
[Feature Request] Merge with webm-writer-js to support audio and video recording to WebM

### ISSUE THREAD

**Issue by guest271314** [chris-rudmin/opus-recorder#218]
Consider a Project to merge opus-recorder with https://github.com/thenickdude/webm-writer-js to support audio and video recording to WebM container.

- https://github.com/thenickdude/webm-writer-js/issues/1
- https://github.com/kbumsik/opus-media-recorder/issues/23

**Comment by chris-rudmin** [comment]
It’s not in my power to merge this code into other peoples repositories. Opus-media-recorder already records opus.

**Comment by guest271314** [comment]
Am not requesting to brute-force merge in the sense of a `git` merge. Am requesting that a Project be started to merge the respective portions of code in order to write the Opus encoded by this repository into the WebM container that webm-writer.js produces for video. Does that make sense?

**Comment by guest271314** [comment]
Just asking before write the entire code from scratch. Since the two existing projects already have working code, the only part that really needs to be done is writing the output from this repository to the WebM container the webm-writer.js produces, resulting in a media recorder written primarily in JavaScript.

**Comment by chris-rudmin** [comment]
@guest271314 I am not interested in investing time into such a project, but feel free to reach out to me if you have questions while merging the two code bases.

**Comment by guest271314** [comment]
That is why reached out to you here, now. 

Just asking maintainers of existing repositories, e.g., https://github.com/GoogleChromeLabs/webm-wasm in an attempt to write as little code as possible to achieve the goal. 

By Project mean https://github.com/chris-rudmin/opus-recorder/projects, where the resepective interested parties (front-end developers at large) can contribute at will.

There is more than likely considerably interest in such a project: a configurable media recorder written primarily in JavaScript.

In lieu of no interest or time by maintainers of the respective projects, on own will probably first try to pipe output from `AudioWorklet` to `opusenc`, convert captured video frames to VP8 bitstream, then merge to a Matroska (WebM) container using `mkvmerge`, then provide the resulting file to JavaScript.

Just had a notion that you might be interested in such an extension of your project, so filed this issue. Cheers.

**Comment by chris-rudmin** [comment]
You are likely better to start with opus-media-recorder instead of this library as it is already built to record to a webm container using webassembly (compiled from native sources instead of written in javascript).

**Comment by guest271314** [comment]
Already filed an issue at that repository, listed above. No movement thus far. Here, have had success achieving requirements using Native Messaging and Native File System (e.g., https://github.com/guest271314/native-messaging-mkvmerge, https://github.com/guest271314/captureSystemAudio) for the ability to use native applications (downloaded and compiled if not installed) then get the result back in JavaScript.

**Comment by guest271314** [comment]
Able to pipe output from `espeak-ng` to `opusenc` at https://github.com/guest271314/native-messaging-espeak-ng and get the result at any web page. Ideally the goal is to write the entire application in JavaScript, as some might not be comfortable using Native Messaging and native applications in the manner that use them in the above repositories. However, if that is not possible, will use what has been successful in the past; write files locally, use native applications, get result as one or more files. Do not want to take up any more of your time. Will carry on and get it done, by any means necessary.
