### ISSUE TITLE
Is it possible to add an 'abort/cancel' method and an 'onAbort/onCancel' listener?

### ISSUE THREAD

**Issue by jaxtheking** [chris-rudmin/opus-recorder#219]
Thanks for providing us with this awesome library, and good job on the recent updates.
I was wondering if you'd be open to add a new method and listener as per the title - similarly to what the HTML5 SpeechRecognition API does? It basically would mimic the stop method, expect for starting the encoder - maybe tidying other loose ends.

A simple use case: I have a voice recorder which auto-stops if no sound (above a certain dB) is detected for 3s. At that point, I'd like to discard the current recording and for the recorder/worker to be ready to be initiated again.

I already do that by (incorrectly) using the pause method and the onPause listener where I close the recorder and the mediaStream - but it'd be cleaner to have a specific method for this.
This is a mere suggestion but I hope you'll give it your consideration.

**Comment by chris-rudmin** [comment]
I don't quite understand the use case.  Can't you use `stop()` and discard the data?

**Comment by jaxtheking** [comment]
Sure, I could do that... however data is processed in the onDataAvailable listener which is not aware of my intentions to cancel the recording/discard the data. Of course, I can add a flag to tell the listener whether the data needs to be discarded or passed on.

I understand that in my case this may seem trivial (as I only process a 3s audio), but if the use case was different (users wanting to cancel a much longer recording as not to their satisfaction/got interrupted), probably the benefits of having an abort method would be more evident (saving time, memory & computations by not running the encoder at all).

**Comment by chris-rudmin** [comment]
The encoder is running in real time. An abort method would not be able to
save any resources

**Comment by jaxtheking** [comment]
Sorry then, I definitely missed that fact.
Thanks anyway for indulging me!
