### ISSUE TITLE
Need help on Making syncable recordings with this recorder

### ISSUE THREAD

**Issue by numerized** [chris-rudmin/opus-recorder#220]
Hello here, I want to check with you how to solve a very annoying problem I am facing.

I am trying to record 30min of voice on my Android app and I get a 29min57s recording, I don't understand why, it's very important because I have to sync and mix few locally recorded files together and produce a conversation out of many local microphones.

Why do you think there's a time drift ? Am I losing frames because of some other process running at the same time in the app ?

What can I do to get a proper time synced recording ?

Thanks a lot

**Comment by chris-rudmin** [comment]
A few possible reasons.

Do you start your timer when the start() promise resolves?

You might also be losing 80ms at the beginning which is used for decoder
sync. Also possible to lose 20ms at the end. I think the last buffer if not
full we discard it.

If you use encoder in streaming mode, every page (800 ms) you can receive
the granule position which you can use to determine the recording length

**Comment by numerized** [comment]
why start() has to be initiated by a click? other recording libs ask for a stream or a audio node on a click first and then we can start programatically the start when we want, do you have a workaround for this ?

**Comment by numerized** [comment]
I am asking because I am getting  

```DOMException: The user aborted a request.```

**Comment by chris-rudmin** [comment]
User needs to grant permissions for the mic

**Comment by numerized** [comment]
but, I do this.

**Comment by chris-rudmin** [comment]
Check that the encoderPath is valid.

**Comment by numerized** [comment]
I've passed my webrtc source node to the recorder I am able to record now with WebRTC live.
Thanks it works, I'm now checking if I can get rid of this time drift.
I'll update you

**Comment by numerized** [comment]
Could it be my Android that is somehow CPU saturated and loses frames or something like this?
What parameters would make this process less time drift prone in your options list?

**Comment by chris-rudmin** [comment]
If you hear glitching in the audio, It probably means you are dropping
frames. You can try and play with resampler quality options and encoder
options for lower latency. The encoder loop needs to complete within 3ms or
you will start losing frames.  On a pc this loop usually completes In under
1 ms.

**Comment by chris-rudmin** [comment]
If you record a performance profile while recording, you can validate that
hypothesis.

**Comment by numerized** [comment]
Cool! Finally a clear reply from a lib maker! Thanks I tried absolutely all libraries!
My app does many things at the same time while recording, I'll try this profiler soon

**Comment by chris-rudmin** [comment]
If that seems to be the case, you can try reducing the frame size from 20ms
to 10ms which may or may not help.

**Comment by numerized** [comment]
I'm recording a performance profile right now.
Then I'll try that frame size change

**Comment by numerized** [comment]
![image](https://user-images.githubusercontent.com/166829/91615577-31e0ea80-e984-11ea-81ce-398a4db87469.png)

Seems like I have fps drops. Could it be responsible for recording frame losses ?

**Comment by chris-rudmin** [comment]
Listen to the recording where you have FPS drops. If you hear glitching
then you are dropping audio frames.

**Comment by numerized** [comment]
yes I can hear that yes.

**Comment by numerized** [comment]
I tried with : 

```encoderFrameSize: 10,
          resampleQuality:0,
          encoderComplexity:0```

**Comment by numerized** [comment]
I have 10s missing for a 20min recording usually

**Comment by numerized** [comment]
I've only let the most important features of my app, and I have same frame drops

**Comment by numerized** [comment]
can I play with other parameters ?

**Comment by chris-rudmin** [comment]
You might try `encoderApplication: 2051` for restricted low delay. I'm not sure if it will help in your scenario.

**Comment by numerized** [comment]
I'm now playing with the `encodedSamplePosition` option and I comparing it to the actual time, I can see the drift building up in a non-linear way on Android 10 galaxy s9 and not on Huawei android 8.

I've set all encoder options to minimal latency.

What else can I try ?

buffers?

**Comment by chris-rudmin** [comment]
Two options:
- You could try and disable AudioWorklets and use the older ScriptProcessor implementation which uses much much larger buffers (higher latency)
- We can try and optimize any problematic code.  In your performance profile, does it align with garbage collection?  We might be able to find where memory is being allocated and garbage collected, and then re-use memory to avoid the garbage collection.

**Comment by chris-rudmin** [comment]
Another option:  If your users will be using chrome 84 or newer, we can try a build with SIMD optimizations enabled (currently they are disabled). Theoretically, it should run faster in chrome.

**Comment by numerized** [comment]
Thanks man!

It's so important to me and my team it's the main festure of our business model and I'll be to send you a donation for your help on this.

I've already disabled all parallel tasks to let only webrtc and recorder working, I'm now going to try your 6.2.0 version and report here.

Thanks for your help. I've opened your code and I liked it a lot.

**Comment by numerized** [comment]
ok so 6.2.0 is not helping, I have 2s time drop in a 2min recording. I can see the time shift with `encodedSamplePosition` 

I'm interested about this SIMD optimisation, can I do it myself ?

**Comment by numerized** [comment]
Just for information, the following repo is the only JS recorder I could find (I tried them all really crazy...) producing accurate time recordings but is producing glitchy recordings on Android AND on desktop, my next step will be to try to fix this repo to remove audio glitches

https://github.com/higuma/web-audio-recorder-js

**Comment by chris-rudmin** [comment]
@numberized You can build the sources yourself and enable SIMD. The flag goes into the makefile step with emconfigure.  For libspeex, add `--enable-sse` flag.  For libopus replace `--disable-intrinsics` with `--enable-intrinsics`

**Comment by numerized** [comment]
hello Chris, 

So I'm trying to build myself from sources, so far I cannot bypass this problem:

```
Kevins-MBP:opus-recorder redloko$ npm run make

> opus-recorder@8.0.3 make /Users/redloko/00_Github/opus-recorder
> make

cd ./opus; ./autogen.sh
Updating build configuration files, please wait....
glibtoolize: putting auxiliary files in '.'.
glibtoolize: linking file './ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
glibtoolize: linking file 'm4/libtool.m4'
glibtoolize: linking file 'm4/ltoptions.m4'
glibtoolize: linking file 'm4/ltsugar.m4'
glibtoolize: linking file 'm4/ltversion.m4'
glibtoolize: linking file 'm4/lt~obsolete.m4'
configure.ac:38: installing './compile'
configure.ac:33: installing './missing'
Makefile.am:316: warning: '%'-style pattern rules are a GNU make extension
Makefile.am:319: warning: '%'-style pattern rules are a GNU make extension
Makefile.am: installing './depcomp'
cd ./opus; emconfigure ./configure --disable-extra-programs --disable-doc --enable-intrinsics --disable-rtcd --disable-stack-protector
emconfigure: error: BINARYEN_ROOT is set to empty value in /usr/local/Cellar/emscripten/1.40.1/libexec/.emscripten
make: *** [opus/.libs/libopus.a] Error 1
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! opus-recorder@8.0.3 make: `make`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the opus-recorder@8.0.3 make script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/redloko/.npm/_logs/2020-09-01T09_27_33_878Z-debug.log
```

**Comment by chris-rudmin** [comment]
Looks like emscripten config error.  Did you add the emscripten env
variables to your PATH? `source ./emsdk_env.sh`. check you have all the
dependencies installed for emscripten `./emcc -v`

**Comment by numerized** [comment]
yeah sorry to remove my comments I was able to go forward, 
now I have another issue, I'll have a look into it soon.

I have to update you, on the sync issue, I have been able to reduce it drastically with increased buffer and lower complexity.
It works much better and super consistently.

Thanks for your help, I'll be trying the SIMD optimizations soon.

Are you looking for a job ? even part time ?

How can we keep in touch outside of this repo ?

**Comment by chris-rudmin** [comment]
@numerized I updated my github profile with my contact info.

**Comment by chris-rudmin** [comment]
> Are you looking for a job ? even part time ?

I am accepting contract work at the moment. Contact me for more details.

**Comment by chris-rudmin** [comment]
@numerized Any success?  I'll close this issue out. Feel free to reopen it if you need some more support.

**Comment by numerized** [comment]
yes all works well thanks, just played with few parameters, I'll post here the config to achieve proper recording on lower end devices.
