### ISSUE TITLE
global is undefined on mobile devices browsers

### ISSUE THREAD

**Issue by MrdUkk** [chris-rudmin/opus-recorder#222]
i have verified this on two phones (android 8 and android 9) and one tablet (android 9).

first line in recorder.js need single line
var global = global || window;
right before
var AudioContext = global.AudioContext || global.webkitAudioContext;
and all is working cross-platform.

**Comment by chris-rudmin** [comment]
Are you using the minified sources? `global` is an object created when compiling to UMD using webpack.  Can you please specify the browser and version as well as the specific error and line number?

**Comment by MrdUkk** [comment]
i'm using npm package (yes, it's minified) in VUE 2.x project hosted on nginx web-server. but talking about source files
so without 'var global = global || window;' before var AudioContext. it is working only in PC windows browsers but not in mobile.
your function Recorder.isRecordingSupported() returning FALSE. 

mobile and tablet browsers is google chrome last versions (up to date from google play).  PC Windows google chrome last versions too. for example 86.0.4240.183.

i can share demo link privately but don't find your email.

**Comment by chris-rudmin** [comment]
Unfortunately I don't have an android device to test with. Can you verify if the example page works on your android device?
https://raw.githack.com/chris-rudmin/opus-recorder/master/example/encoder.html

**Comment by MrdUkk** [comment]
in pure html its okay anyway. the problem arrive after using npm component

**Comment by chris-rudmin** [comment]
if you are doing `import Recorder from 'opus-recorder'` it should be importing `dist/recorder.min.js` so the behaviour should be the same as the example page. I suspect the error might be coming from your implementation, if somehow you are importing `src/recorder.js`.

**Comment by MrdUkk** [comment]
may be. im not JS expert. but by proposed solution is fix-for-all probably use-cases. Does it break something? 

im use npm package like mention before in Vue 2.x project. in specific component (not in app.vue!). 
and it's throwing exception without my addition.

component.vue
<template>
...
</template>
<script>
import Recorder from 'opus-recorder'
export default {
    name: 'test',
    data() {
      return {
        recorder: null,
        options: { bufferLength: 256,
                    numberOfChannels: 2,
                    encoderSampleRate: 48000,
                    encoderBitRate: 32000,
                    encoderComplexity: 0,
                    resampleQuality: 0,
                    encoderFrameSize: 20,
                    maxFramesPerPage: 2,
                    rawPacket:true,
                    streamPages: true
                 }
      }
    },
    methods: {
      togglebutton() {
                this.recorder = new Recorder(this.options);
     }
   }
}
</script>

**Comment by chris-rudmin** [comment]
The use of option `rawPacket` In your example implies to me that you are not using my library as it has been distributed. Please reopen the issue when you can provide a reduced test  case which reproduces the error
