### ISSUE TITLE
Audio crackling/stuttering when opus encoded

### ISSUE THREAD

**Issue by lordadamson** [chris-rudmin/opus-recorder#223]
Hi,

I have no experience with audio whatsoever but I've used this awesome library for my website.

All the recordings I'm receiving are awesome, except for one person, her recordings are crackling and a little sped-up.

luckily I was able to get in touch with the person. I asked her if she had an issue on any other app. I asked her to record on another website to see if the same issue occurs, but unfortunately the issue only happens on my website.

Her phone is Samsung Galaxy J5 and she's using the default Samsung internet browser.

Let me know what other info can I provide to help fix this.

**Comment by lordadamson** [comment]
Update: The issue only happens on Samsung internet browser. When she tried chrome it worked fine. 🤔

**Comment by chris-rudmin** [comment]
Sounds like the opus recorder is dropping frames due to the Samsung Internet browser performance. The encoder is required to finish its encoder loop within 4ms. If it exceeds 4ms then the encoder will start dropping frames. Best you can do is to try and optimize your settings to reduce the load requirements on your clients.

ie. Reduce from stereo to mono, reduce the resample quality etc. 

Hope that helps.

**Comment by lordadamson** [comment]
Hey, thanks for the response!

I understand that requirement in real-time applications. But the application isn't really real-time, I can wait a little for the encoding if the device is not performant. Can this become an option or something? Is this something under our control or is it a Libopus thing?

**Comment by lordadamson** [comment]
I'm willing to make a PR if the answers to these questions say that it's possible and you're willing to accept it :smile:

**Comment by chris-rudmin** [comment]
@lordadamson Try using version v6.2.0.  This used a message passing mechanism which would buffer all the frames. Version v7 and up was changed to use AudioWorklet nodes

**Comment by lordadamson** [comment]
Ok, thanks :D
