### ISSUE TITLE
Record for exact amount of time

### ISSUE THREAD

**Issue by samanmohamadi** [chris-rudmin/opus-recorder#226]
Hi, Is there any way to change the recorder to record for a fixed duration time?
I want to set the duration before recording and get the exact duration in output. 
currently, I have to trim output audio some times after recording.

**Comment by chris-rudmin** [comment]
There is not currently a method to do this. One workaround is to stream the encoded pages and watch the recorded length via the value of `granulePosition`.  The recording length granularity is limited to page size (by default 480ms). There is also a sync time at the beginning of the encoded audio where you will not get any playback. By default this is 80ms .

**Comment by chris-rudmin** [comment]
Here was a previous discussion about this topic: https://github.com/chris-rudmin/opus-recorder/issues/220
