### ISSUE TITLE
DOMException: The user aborted a request

### ISSUE THREAD

**Issue by pitonoved** [chris-rudmin/opus-recorder#230]
First of all, thanks for the plugin! I have a problem. In my Vue.js app when I call `const rec = new Recorder({ encoderPath })` - I get error `Uncaught (in promise) DOMException: The user aborted a request` in Chrome. There is no recording device selection. What could it be for?

**Comment by chris-rudmin** [comment]
@pitonoved That error is thrown when the user has disallowed microphone permissions. It might also occur if there is no microphone input on the device.

**Comment by pitonoved** [comment]
I don't understand why, because it doesn't even ask permission. At the same time, if I manually `navigator.mediaDevices.getUserMedia` then the browser asks for the microphone as expected.

**Comment by pitonoved** [comment]
> 
> 
> @pitonoved That error is thrown when the user has disallowed microphone permissions. It might also occur if there is no microphone input on the device.

This may be due to that `encoderWorker.min.js` is not loading correctly?

**Comment by chris-rudmin** [comment]
@pitonoved If you can provide me a reduced test case which reproduces the error, I can take a look.

**Comment by chris-rudmin** [comment]
@pitonoved Yes, if the path to the worker is incorrect, it will throw this error as well.

**Comment by pitonoved** [comment]
Thanks for answers. Worker could be uploaded, but now there is a new problem: `Uncaught RangeError: WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.compile, or compile on a worker thread.`

I'm definitely doing something wrong(

**Comment by pitonoved** [comment]
I solved the problem. Thank you and sorry for your time!

**Comment by pitonoved** [comment]
> 
> 
> @pitonoved Yes, if the path to the worker is incorrect, it will throw this error as well.

The only request is that need to handle cases when the plugin does not see the `encoderWorker.min.js`. Now it just continues to execute the script further. I simply didn't incorrectly connect config....

**Comment by C4rb0ngit** [comment]
How did you solve it?

**Comment by pitonoved** [comment]
> 
> 
> How did you solve it?

The problem was in my config. I connected it incorrectly.

**Comment by C4rb0ngit** [comment]
What did you change?

**Comment by pitonoved** [comment]
> 
> 
> What did you change? I have the same problem...

I don't remember anymore, but the final .ts file looks something like this

```import Recorder from 'raw-opus-stream-recorder'
import encoderPath from 'raw-opus-stream-recorder/dist/encoderWorker.min'

export const RECORDER: {
    ondataavailable: (arrayBuffer: any) => void
    onerror: (error: any) => never
    onstart: () => void
    onstop: () => void
    start: () => void
    stop: () => void
} = new Recorder({
    encoderPath,
    streamPages: true,
    rawOpus: true
})
```

**Comment by ara4n** [comment]
I got it to work in vite with:

```
import encoderPath from 'opus-recorder/dist/encoderWorker.min.js?url'
```

**Comment by kkxlkkxllb** [comment]
> I got it to work in vite with:
> 
> ```js
> import encoderPath from 'opus-recorder/dist/encoderWorker.min.js?url'
> ```

thanks, you are such a genius! 
i have tried
```js
import encoderPath from 'opus-recorder/dist/encoderWorker.min.js?worker'
```
but not work
