### ISSUE TITLE
"Dropping a Needle in the Track" [Question]

### ISSUE THREAD

**Issue by SuddenlyHazel** [chris-rudmin/opus-recorder#231]
Hey all - Let me preface this by saving my technical understanding of this might be way off, apologies in advance if so.

At a very high level I'm trying to work out how to stream ogg / opus audio to a server, cache a rolling "window" of opus pages, and enable "clients" to drop in at any time to listen. This basically exactly mirrors the layout of something like internet radio.

I'm streaming the data to the server and caching without issues, this library made that short work, great work! However, I'm stuck trying to figure out how to let users "drop in" on the stream. 

My current understanding, is that you should be able to "drop the needle" at any page "page" of ogg/opus. However, I'm having no luck with `AudioContext::decodeaudiodata`.

Can anyone point me in the right direction?

**Comment by SuddenlyHazel** [comment]
After some more reading, I think I have a plan now:

Use the decoder in:
https://www.npmjs.com/package/libopus.js/v/0.0.1

to go from the ogg/opus pages to PCM.

Then it might just be a dance around passing that data into a..
https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/createBuffer

and connect it all up to a `AudioBufferSourceNode`.

**Comment by chris-rudmin** [comment]
@SuddenlyHazel Checkout [MDN](https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/Live_streaming_web_audio_and_video#server-side_streaming_technologies) for some suggestions on server technologies for live streams.

**Comment by SuddenlyHazel** [comment]
@chris-rudmin - Should have added I can't use a traditional server. To keep it short I can only poll my datastore using get-requests.

**Comment by chris-rudmin** [comment]
@SuddenlyHazel You might run into audio glitching if you are switching your buffers in and out (see here: https://github.com/WebAudio/web-audio-api/issues/1825). I would probably try and setup an audio worklet node (or createScriptProcessor for legacy API) to serve the buffered audio. Good luck!

**Comment by chris-rudmin** [comment]
@SuddenlyHazel [StackOverflow reference](https://stackoverflow.com/questions/57583266/audioworklet-set-output-to-float32array-to-stream-live-audio)

**Comment by SuddenlyHazel** [comment]
This is exactly the direction I needed. Thank you so much!!!

**Comment by SuddenlyHazel** [comment]
Howdy again!

I ended up not using ogg / opus for the time being. However, I did get the streaming audio working. Albeit, in a kinda nasty way. Oh well. Leaving a link to my repo in the event others stumble upon this one day. I plan on integrating eventually.

https://github.com/SuddenlyHazel/dfinity-streams


Closing this one out. Thanks again!
