### ISSUE TITLE
Streaming

### ISSUE THREAD

**Issue by WindowsNT** [chris-rudmin/opus-recorder#233]
It seems it can do it, I can't find an exposed function though. Instead of saving internally and/or to file the encoded data, I want to upload it to a server, possibly with $.ajax or similar JS. 

If you don't already have such a function I 'll dig into the code and implement one.

**Comment by chris-rudmin** [comment]
Please read the [documentation](https://github.com/chris-rudmin/opus-recorder/blob/master/README.md) for supported functionality.
