### ISSUE TITLE
Is it possible to stream raw opus data? 

### ISSUE THREAD

**Issue by WindowsNT** [chris-rudmin/opus-recorder#234]
Wrapping in ogg pages creates latency when all I want is to send the packets back to my server. Currently I have to read the stream as ogg, where I could just uncompress the opus frame.

Could there be an option to return the raw opus data instead of an ogg page?

**Comment by chris-rudmin** [comment]
@WindowsNT This is not a supported feature.  Look in the pull requests for some implementations that might suit your needs.
