### ISSUE TITLE
ScriptProcessorNode is deprecated

### ISSUE THREAD

**Issue by rotem925** [chris-rudmin/opus-recorder#241]
Hi,
I'm getting warnings from latest Chrome on macOS that ScriptProcessorNode is now deprecated, and we should use AudioWorkletNode.
Any idea when ScriptProcessorNode will be removed? Are there any plans to support AudioWorklet?
![Screen Shot 2021-06-05 at 11 54 56](https://user-images.githubusercontent.com/248898/120886135-154d9f00-c5f5-11eb-812c-db4d3447f3c3.png)

**Comment by chris-rudmin** [comment]
@rotem925 Can you please confirm which version of opus-recorder you are using and which version of chrome shows you the error?

**Comment by chris-rudmin** [comment]
@rotem925 AudioWorklets are already supported. ScriptProcessorNode is only used as a fallback.

**Comment by rotem925** [comment]
Sorry @chris-rudmin ,im using an older version. Just saw the fallback in the code.
Thanks for the quick response. I'm closing the issue
