### ISSUE TITLE
Cant compile speex when running on macOS m1 chip

### ISSUE THREAD

**Issue by rotem925** [chris-rudmin/opus-recorder#243]
Hi,
I'm trying to compile from the local sources. I'm using the new mac with the m1 chip
It seems like there is missing compatibility with speex and neon.
I get this error: resample_neon.h:134:12: error: unknown register name 'q0' in asm

After seeing this reference: https://speex-dev.xiph.narkive.com/nTffejbI/fwd-cannot-compile-speexdsp-1-2rc3-on-arm64
Adding the --disable-neon flag when configuring speex, did the trick.
Is this something that can be fixed in the current code?

Thanks!!

**Comment by chris-rudmin** [comment]
@rotem925 Yes the `--disable-neon` flag is required to build. #242 will fix it.

**Comment by rotem925** [comment]
Superb! Thanks!

**Comment by chris-rudmin** [comment]
fixed by #242
