### ISSUE TITLE
How to use with Vite?

### ISSUE THREAD

**Issue by leochoo** [chris-rudmin/opus-recorder#251]
I ran into the same issue shown here.

https://githubmemory.com/repo/chris-rudmin/opus-recorder/issues/230

`Uncaught RangeError: WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.compile, or compile on a worker thread.`

It seems that I need to somehow load the file like how `Getting started with webpack` suggests in README, except I need to do it on Vite. 

I was wondering if you could give us hints on where to look at.

**Comment by karlmacklin** [comment]
@leochoo Did you ever solve this? I'm in the same situation.

**Comment by leochoo** [comment]
> @leochoo Did you ever solve this? I'm in the same situation.

Never did mate. I just used the native MediaRecorder API and other React libraries like react-media-recorder. If u want I can share what I've done.

**Comment by karlmacklin** [comment]
> 

Thanks, that's ok. I ended up doing basically the same thing, and a lot of stuff with AudioContext.

**Comment by ara4n** [comment]
To make it work in vite you import the worker as:

`import encoderPath from 'opus-recorder/dist/encoderWorker.min.js?url'`

You don't need to make changes to vite.config.ts (unlike when using webpack).

**Comment by admfrenchdev** [comment]
> To make it work in vite you import the worker as:
> 
> ```js
> import encoderPath from 'opus-recorder/dist/encoderWorker.min.js?url'
> ```
> 
> You don't need to make changes to vite.config.ts (unlike when using webpack).

Hi @ara4n . I know it's been a while, but could you be more precise on this please ? I don't get what this `encoderPath` refers to :/ And still having issues with wasm.
