### ISSUE TITLE
The first recording is not saved in Safari on IOS 15.1 

### ISSUE THREAD

**Issue by vsokolovskiy** [chris-rudmin/opus-recorder#252]
Steps to Reproduce: 

1. Start recording.
2. When the popup shows up, requesting permissions, grant them.
3. After the red microphone icon appears on the tab, record some speech
4. Stop the recording.

The issue seems to be that `recorder.ondataavailable` is not firing on first recording. 

After this initial recording, the subsequent recording works fine. 

Let me know if you need any additional info. Thanks!

**Comment by davidmanson** [comment]
Same problem here, how did this topic closed ? Thank you.
