### ISSUE TITLE
building and running on windows 10

### ISSUE THREAD

**Issue by MartinBarker** [chris-rudmin/opus-recorder#256]
Hello, I am trying to run this repo to view some examples of recording wav files locally.
I have clones and been running the commands in windows linux subsystem terminal. But the `npm run make` command is failing once it gets to emconfigure:
```
checking sys/audioio.h presence... no
checking for sys/audioio.h... no
checking for cos in -lm... yes
./configure: line 10227: syntax error near unexpected token `FFT,'
./configure: line 10227: `  PKG_CHECK_MODULES(FFT, fftw3f)'
emconfigure: error: './configure --disable-examples --disable-neon' failed (returned 2)
make: *** [Makefile:57: speexdsp/libspeexdsp/.libs/libspeexdsp.a] Error 1
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! opus-recorder@8.0.5 make: `make`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the opus-recorder@8.0.5 make script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I was wondering if anyone has had luck with building and running this repo on windows 10 linux subsystem?
Thanks, M

**Comment by chris-rudmin** [comment]
@MartinBarker I've always had difficulty running autotools on Windows (i'm running mac and ubuntu usually).  If you manage to get it working, post the steps here, and i'm sure it will be helpful to someone else.

**Comment by chris-rudmin** [comment]
If you can't get it working on native windows, you should be able to run the build inside a container.

**Comment by MartinBarker** [comment]
Thanks for the advice, it does work and complete `npm run make` on my ubuntu computer.
Different question, but I was wondering if you knew how I could record audio using the example/waveRecorder.html file in this repo? I tried just opening the html file it in chrome but it gives an err when trying to start recording:
![image](https://user-images.githubusercontent.com/27025504/149047377-eadc6eca-1bc5-494e-84b2-7b83daf0b22b.png)

is there a different way I'm supposed to serve the file on say a local server for example? Some command besides `npm run make` maybe? Thanks

**Comment by MartinBarker** [comment]
ill post it in a new issue
