### ISSUE TITLE
Error running waveRecorder.html example

### ISSUE THREAD

**Issue by MartinBarker** [chris-rudmin/opus-recorder#257]
I was wondering how I could record audio using the example: `example/waveRecorder.html` file included in this repo.
I have cloned this repo, ran npm i, and npm run make with no errors.
I tried just opening the html file it in chrome but it gives an err when trying to start recording:
![image](https://user-images.githubusercontent.com/27025504/149053087-26c3a5ec-033e-40d4-84bd-ef7db862917c.png)

is there a different way I'm supposed to serve the file on say a local server for example? Some command besides npm run make maybe? Thanks

**Comment by chris-rudmin** [comment]
Recording only works on pages served over https. You can use [ngrok](https://ngrok.com/download) to proxy https to your local machine.

**Comment by chris-rudmin** [comment]
I don't have a npm command for starting a local server, but you can use `python -m http.server` (python 3)
