### ISSUE TITLE
using waveform-playlist with opus-recorder

### ISSUE THREAD

**Issue by MartinBarker** [chris-rudmin/opus-recorder#258]
Hello, I am working on a high quality fork of opus-recorder for trying to achieve lossless wav quality through a web interface:
https://github.com/MartinBarker/opus-recorder-min
Opus-recorder is by far the highest quality web audio I've been able to produce yet, but I want to connect the opus-recorder to work with the robust waveform-playlist JavaScript package:
https://github.com/naomiaro/waveform-playlist

From the opus-recorder dev standpoint, would connecting these two repos together work? Or would there be an underlying issue of compatibility

**Comment by chris-rudmin** [comment]
@MartinBarker I don't see any reason it would not work.  Good luck!
