### ISSUE TITLE
Convert 16 bit signed int to 32 bit float

### ISSUE THREAD

**Issue by Micrufun** [chris-rudmin/opus-recorder#265]
At this line:

https://github.com/chris-rudmin/opus-recorder/blob/fdfdadeeb9bc9d045c59dc75ebefed390e4ad6dc/example/fileEncoder.html#L62

We are conversing an `Int 16` value to a `Float 32` value between `-1` and `+1`. It makes sense to divide the `Int 16` value over its max possible which is `2^16/2` i.e. `32768`.

# Question 1

But I don't understand the `+ 0.5` statement. Why are we adding that? Does it have a huge effect on accuracy? What happens if we remove `+ 0.5`?

# Question 2

Another question is that, can we use the same approach to get `Float 32` between `-1` and `+1` from `Int 32`, `Int 64` , `Int 128` and so on?

**Comment by Micrufun** [comment]
Also, there is this approach which is a bit different: https://stackoverflow.com/a/35248852/3405291

**Comment by Micrufun** [comment]
Test indicates that this code works too:

```js
var maxPossible = 2**16/2; // Signed 16 bit is the data resolution.
... = (totalFile[i + j]) / maxPossible;
```
Not sure about the precision difference.

**Comment by chris-rudmin** [comment]
@Micrufun Indeed there are many different ways to convert Int to float.  The additional 0.5 is to convert an asymmetric space (-32768, 32767) into a symmetric space(-1,1) by shifting the 0 crossing point

**Comment by Micrufun** [comment]
If by any chance the example is going to be extended to include any *channel count* and *bit depth*, this is a tested modification which might help:

```js

    function chunkBuffers(arrayBuffer, chunkLength, channelCount, bitDepth){
      var chunkedBuffers = [];

      var maxPossible = 2**bitDepth/2; // Bit depth is the data resolution.
      console.log('MAX POSSIBlE DATA VALUE', maxPossible);

      var totalFile = new Int16Array(arrayBuffer);
      // Skip wave header; 44 bytes
      for (i = 22; i < totalFile.length; i += chunkLength) {

        // Convert 16 bit signed int to 32bit float
        var bufferChunk = new Float32Array(chunkLength/channelCount); // Just keep 1st channel. So, divide length.
        var idx = 0; // To skip 2nd channel.
        for (j = 0 ; j < chunkLength ; j+=channelCount) { // Just keep 1st channel by `j+=`.
          bufferChunk[idx] = (totalFile[i + j]) / maxPossible;
          idx++;
        }

        chunkedBuffers.push([bufferChunk]) ;
      };

      return chunkedBuffers 
    };
```

Then, calling it by:

```js

chunkBuffers(arrayBuffer, bufferLength, 2, 16).forEach(...)
```

Or:

```js
chunkBuffers(arrayBuffer, bufferLength, 1, 16).forEach(...)
```

**Comment by chris-rudmin** [comment]
@Micrufun By shifting the 0 crossing point, we distribute the conversion precision across the whole range [-1.1].  In the other implementation you shared, the negative values and positive values are treated separately. the 0 crossing point is maintained, but the negative values will have slightly more precision than the positive values.  Likely the differences between the two conversions are inaudible

**Comment by Micrufun** [comment]
Right. Finally, I considered the desirable symmetry:

```js
      // Shifting the 0 crossing and keeping the two halves of the waveform symmetric,
      // by `+-0.5` statements:
      bufferChunk[idx] = (totalFile[i + j]+ 0.5) / (maxPossible-0.5);
```

**Comment by chris-rudmin** [comment]
@Micrufun Watch out for 8 bit wavs which use unsigned Integers

**Comment by chris-rudmin** [comment]
I referenced [dsprelated.com](https://www.dsprelated.com/forums) forums frequently when I was in search of different algorithms / tradeoffs.
