### ISSUE TITLE
Is it possible to Decode two audio sources

### ISSUE THREAD

**Issue by kered59** [chris-rudmin/opus-recorder#278]
Hello everyone and in advance thank you for your time, please excuse me if this is the incorrect location to pose this question,

In the program I am building I need to receive multiple different sources of Encoded Audio Packets which need to be decoded using a single Web Worker Decoder. Currently when I post a message to the Decoder for a single stream it outputs audio as intended, crystal clear. 

However once a second stream to be decoded is introduced, it causes hiccuping and audio stuttering even if the decoded packets are not being processed after the Decoder has posted them back.

This could be a misunderstanding relating to my naivety working with Opus and this library in particular. 

To be as clear as I can I have a single stream over network operating as intended utilizing the Recorder module built in, however attempting to decode multiple sourced streamed packets through a single Decoder causes audio playback issues even though it is decoding them drastically quicker than the play length of the packet itself. This persists even at much larger packet lengths (2+ seconds per packet) which leads me to believe that because of the instantiation of the Decoder itself requiring specific packet types at launch could simply fail to handle multiple varying streams simultaneously.

Any insight would be greatly appreciated and if this library is incapable of handling my request than an alternative which outputs a Float32Array would be very helpful.

**Comment by chris-rudmin** [comment]
If you have multiple streams and want to use a single decoder, you will need to recombine the streams using the multistream api. before decoding. The easier solution is to instantiate a second decoder, and decode the two streams independantly.

**Comment by kered59** [comment]
Looking through Opus literature I was wary that this would be the case, thank you for your response and to followup I presume that the mutlistream functions are not exposed in this library correct?

**Comment by chris-rudmin** [comment]
Multistream functions are not exposed in this library.

**Comment by kered59** [comment]
Thank you again for your time.
