### ISSUE TITLE
Glitches in waveform on Chrome

### ISSUE THREAD

**Issue by GerCarney** [chris-rudmin/opus-recorder#280]
Hello!

I've been using opus-recorder for a couple of years in a UI that's used to record voice actors.

The sound engineers involved had flagged that they occasionally get little pops and artefacts in the recordings. Sometimes they'd record for hours without issues. Other times 20 recordings in a row could have pops.

I found it difficult to recreate the problem initially, but I've landed on a pretty consistent approach:

- Play a 200hz sine wave into the microphone while recording
- Drag the file into a tool that displays spectrograms

<img width="2029" alt="image" src="https://github.com/chris-rudmin/opus-recorder/assets/13680138/0de984a2-e79f-4ddd-8097-6ae3f853dcbb">

Almost every 10+ second recording in Chrome has these gaps in the waveform. Sometimes they're audible, sometimes they're not, depending on where they land in the wave.

I've seen them very, very rarely in Firefox, but never in Safari.
It doesn't happen in any other audio software (Adobe Audition, Logic Pro, ProTools)

I was able to recreate the issue using a minimal example.
Just the Recorder + WaveWorker and a Record/Stop button in plain HTML + JS

```
    const mediaRecorder = new Recorder({
      monitorGain: 0,
      recordingGain: 1,
      numberOfChannels: 1,
      encoderPath,
      wavBitDepth: 24,
      mediaTrackConstraints: {
        echoCancellation: false,
        noiseSuppression: false,
        autoGainControl: false,
      },
    });
 ```

It happens regardless of bitdepth, buffer size or sample rate.
I've tried various permutations of (16bit, 24bit, 32bit) + (Buffer sizes from 2 -> 56k) + (44khz and 48khz).

We've reproduced it on multiple machines (All either M1 MacBooks or Intel Mac Pros), with multiple audio interfaces and mics (internal mics, USB mics, and through Audio Interfaces).

I'm happy enough to use other browsers for our use-case, but I thought I'd post anyway, just in case anybody has any ideas for what the cause might be!

**Comment by chris-rudmin** [comment]
Looks like 0's got added (the waveform would be continuous if not for the 0's) which would point to a buffer underrun in the stream. Checking the chromium bugs points to garbage collection on the main thread as a potential culprit https://issues.chromium.org/issues/40573297.

**Comment by GerCarney** [comment]
Interesting! I should have mentioned that I did a lot of digging around in the profiler trying to find other events (like garbage collection) that synced up, but it wasn't always the case.

Plus, not every example fits the description of "continuous if not for the 0's". They come in all shapes and sizes!

![image](https://github.com/chris-rudmin/opus-recorder/assets/13680138/408be0d7-a7b9-4d53-9559-62f3e96a0b4f)
![image](https://github.com/chris-rudmin/opus-recorder/assets/13680138/2033ddb0-e3b5-4bef-b787-b40bb8fc929a)

But I'll have a look at those threads and see if it matches what I'm seeing. 

Thanks for the quick reply, Chris!  Much appreciated

**Comment by chris-rudmin** [comment]
Perhaps this might be relevant as well: https://stackoverflow.com/questions/69119160/chromium-audio-worklet-dropouts-some-initially-then-occasionally-in-30s-interv

**Comment by GerCarney** [comment]
Quick update on this. We didn't end up having any luck with fixing this, but we've just moved to using Safari for our recording work, and haven't had any further issues. But thanks for the help!
