### ISSUE TITLE
Investigate Libogg

### ISSUE THREAD

**Issue by chris-rudmin** [chris-rudmin/opus-recorder#50]
Perhaps replace custom ogg implementation with an emscripten compiled version of libogg

**Comment by kbumsik** [comment]
Hi,
Firstly, thanks for your awesome work! I'm currently working on [MediaRecorder polyfill](https://github.com/kbumsik/opus-media-recorder) based on your code. I recently replaced your Ogg implementation with libogg. I hope this would bring more stable Ogg support.

If you are interested in using libogg, I believe this is a good reference to begin with :)

**Comment by chris-rudmin** [comment]
I will not add libogg to opus-recorder. Please see https://github.com/kbumsik/opus-media-recorder for a native libogg implementation.
