### ISSUE TITLE
webm opus to ogg opus?

### ISSUE THREAD

**Issue by lepinsk** [chris-rudmin/opus-recorder#90]
Hey Chris,

Given the [ongoing issues](https://bugs.chromium.org/p/chromium/issues/detail?id=734290) with recording direct from a ScriptProcessor, I'm wondering whether you've considered how feasible it would be to re-containerize the webm files that come out of MediaStream (I see you looked into this briefly in #86). As I understand it, it should be possible to move between ogg-opus and ogg-webm by simply writing the data into a new container.

**Comment by chris-rudmin** [comment]
@lepinsk  I'm not familiar enough with WebM containers to say how feasible it is. I'll keep an eye on those open issues to see what comes. If you have some good resources on the WebM container spec, send it my way.

**Comment by lepinsk** [comment]
Sure thing – I've been taking a peek around a bit myself. I'll let you know what I find.

**Comment by octavn** [comment]
>it should be possible to move between ogg-opus and ogg-webm

You mean between Opus in ogg container to Opus in webm container ?

**Comment by chris-rudmin** [comment]
@lepinsk I will likely never add webm container support.  Please see https://github.com/kbumsik/opus-media-recorder for a very nice browser polyfill with webm container support.
